const many = (f, fn, count = 40) => f.helpers.multiple(fn, { count });
export const cases = [
  ['accountNumber', (f) => f.finance.accountNumber()],
  ['accountNumber/5', (f) => f.finance.accountNumber(5)],
  ['accountNumber/opts', (f) => f.finance.accountNumber({ length: 12 })],
  ['accountName', (f) => f.finance.accountName()],
  ['routingNumber', (f) => f.finance.routingNumber()],
  ['routingNumber/many', (f) => many(f, () => f.finance.routingNumber())],
  ['amount', (f) => f.finance.amount()],
  ['amount/opts', (f) => f.finance.amount({ min: 5, max: 10, dec: 0, symbol: '$' })],
  ['amount/dec4', (f) => f.finance.amount({ min: -1000, max: 1000, dec: 4 })],
  ['amount/auto', (f) => f.finance.amount({ min: 1000, max: 100000000, autoFormat: true })],
  ['amount/auto0', (f) => f.finance.amount({ min: 100, max: 10000000, dec: 0, autoFormat: true, symbol: '€' })],
  ['amount/auto5', (f) => f.finance.amount({ min: -9999999, max: 9999999, dec: 5, autoFormat: true })],
  ['amount/autosmall', (f) => f.finance.amount({ max: 999, autoFormat: true })],
  ['amount/autoneg', (f) => f.finance.amount({ min: -5000, max: -1000, dec: 1, autoFormat: true })],
  ['amount/err', (f) => f.finance.amount({ min: 10, max: 1 })],
  ['amount/errdec', (f) => f.finance.amount({ dec: -1 })],
  ['transactionType', (f) => f.finance.transactionType()],
  ['currency', (f) => f.finance.currency()],
  ['currencyCode', (f) => f.finance.currencyCode()],
  ['currencyName', (f) => f.finance.currencyName()],
  ['currencySymbol', (f) => f.finance.currencySymbol()],
  ['currencySymbol/many', (f) => many(f, () => f.finance.currencySymbol(), 20)],
  ['currencyNumericCode', (f) => f.finance.currencyNumericCode()],
  ['bitcoinAddress', (f) => f.finance.bitcoinAddress()],
  ['bitcoinAddress/many', (f) => many(f, () => f.finance.bitcoinAddress(), 12)],
  ['bitcoinAddress/legacy', (f) => f.finance.bitcoinAddress({ type: 'legacy' })],
  ['bitcoinAddress/segwit', (f) => f.finance.bitcoinAddress({ type: 'segwit', network: 'testnet' })],
  ['bitcoinAddress/bech32', (f) => f.finance.bitcoinAddress({ type: 'bech32' })],
  ['bitcoinAddress/bech32t', (f) => f.finance.bitcoinAddress({ type: 'bech32', network: 'testnet' })],
  ['bitcoinAddress/taproot', (f) => f.finance.bitcoinAddress({ type: 'taproot', network: 'mainnet' })],
  ['bitcoinAddress/testnet', (f) => f.finance.bitcoinAddress({ network: 'testnet' })],
  ['litecoinAddress', (f) => f.finance.litecoinAddress()],
  ['creditCardNumber', (f) => f.finance.creditCardNumber()],
  ['creditCardNumber/many', (f) => many(f, () => f.finance.creditCardNumber(), 20)],
  ['creditCardNumber/visa', (f) => f.finance.creditCardNumber('visa')],
  ['creditCardNumber/Mastercard', (f) => f.finance.creditCardNumber({ issuer: 'MasterCard' })],
  ['creditCardNumber/jcb', (f) => f.finance.creditCardNumber({ issuer: 'jcb' })],
  ['creditCardNumber/diners', (f) => f.finance.creditCardNumber('diners_club')],
  ['creditCardNumber/amex', (f) => f.finance.creditCardNumber('american_express')],
  ['creditCardNumber/custom', (f) => f.finance.creditCardNumber('63[7-9]#-####-####-###L')],
  ['creditCardNumber/slash', (f) => f.finance.creditCardNumber('1234/####/####L')],
  ['creditCardNumber/unknown', (f) => f.finance.creditCardNumber('foo')],
  ['creditCardCVV', (f) => f.finance.creditCardCVV()],
  ['creditCardIssuer', (f) => f.finance.creditCardIssuer()],
  ['pin', (f) => f.finance.pin()],
  ['pin/6', (f) => f.finance.pin(6)],
  ['pin/opts', (f) => f.finance.pin({ length: 1 })],
  ['pin/err', (f) => f.finance.pin(0)],
  ['ethereumAddress', (f) => f.finance.ethereumAddress()],
  ['iban', (f) => f.finance.iban()],
  ['iban/many', (f) => many(f, () => f.finance.iban(), 60)],
  ['iban/formatted', (f) => f.finance.iban({ formatted: true })],
  ['iban/DE', (f) => f.finance.iban({ countryCode: 'DE' })],
  ['iban/GB', (f) => f.finance.iban({ countryCode: 'GB', formatted: true })],
  ['iban/FR', (f) => f.finance.iban({ countryCode: 'FR' })],
  ['iban/MT', (f) => f.finance.iban({ countryCode: 'MT', formatted: true })],
  ['iban/BR', (f) => f.finance.iban({ countryCode: 'BR' })],
  ['iban/empty', (f) => f.finance.iban({ countryCode: '' })],
  ['iban/err', (f) => f.finance.iban({ countryCode: 'XX' })],
  ['bic', (f) => f.finance.bic()],
  ['bic/branch', (f) => f.finance.bic({ includeBranchCode: true })],
  ['bic/nobranch', (f) => f.finance.bic({ includeBranchCode: false })],
  ['transactionDescription', (f) => f.finance.transactionDescription()],
  ['fake', (f) => f.helpers.fake('{{finance.amount({"min":1,"max":5,"symbol":"$"})}} {{finance.iban}} {{finance.pin(6)}} {{finance.creditCardNumber("visa")}}')],
  ['fake/currency', (f) => f.helpers.fake('{{finance.currency.code}} {{finance.currencyName}}')],
];
