const arr = ['a', 'b', 'c', 'd', 'e', 'f', 'g'];
export const cases = [
  ['arrayElement', (f) => f.helpers.arrayElement(arr)],
  ['arrayElement/one', (f) => f.helpers.arrayElement(['x'])],
  ['arrayElements', (f) => f.helpers.arrayElements(arr)],
  ['arrayElements/3', (f) => f.helpers.arrayElements(arr, 3)],
  ['arrayElements/range', (f) => f.helpers.arrayElements(arr, { min: 2, max: 4 })],
  ['arrayElements/all', (f) => f.helpers.arrayElements(arr, 10)],
  ['arrayElements/0', (f) => f.helpers.arrayElements(arr, 0)],
  ['shuffle/inplace', (f) => f.helpers.shuffle([...arr], { inplace: true })],
  ['shuffle', (f) => f.helpers.shuffle(arr)],
  ['weightedArrayElement', (f) => f.helpers.weightedArrayElement([{ weight: 5, value: 'sunny' }, { weight: 4, value: 'rainy' }, { weight: 1, value: 'snowy' }])],
  ['uniqueArray', (f) => f.helpers.uniqueArray(['a', 'a', 'b', 'c', 'c', 'd'], 3)],
  ['uniqueArray/fn', (f) => f.helpers.uniqueArray(() => f.number.int(20), 5)],
  ['multiple', (f) => f.helpers.multiple(() => f.number.int(9))],
  ['multiple/range', (f) => f.helpers.multiple(() => f.string.alpha(2), { count: { min: 1, max: 5 } })],
  ['maybe', (f) => f.helpers.maybe(() => 'yes')],
  ['maybe/0.9', (f) => f.helpers.maybe(() => 'yes', { probability: 0.9 })],
  ['objectKey', (f) => f.helpers.objectKey({ a: 1, b: 2, c: 3 })],
  ['objectValue', (f) => f.helpers.objectValue({ a: 1, b: 2, c: 3 })],
  ['objectEntry', (f) => f.helpers.objectEntry({ a: 1, b: 2, c: 3 })],
  ['enumValue/string', (f) => f.helpers.enumValue({ Red: 'red', Green: 'green', Blue: 'blue' })],
  // A compiled numeric TypeScript enum, with its reverse mappings.
  ['enumValue/numeric', (f) => f.helpers.enumValue({ 0: 'Zero', 1: 'One', 2: 'Two', Zero: 0, One: 1, Two: 2 })],
  ['enumValue/mixed', (f) => f.helpers.enumValue({ 1: 'A', A: 1, B: 'b', '1e3': 'x', '0x1f': 'y', ' ': 'z', NaN: 'n' })],
  ['enumValue/empty', (f) => f.helpers.enumValue({})],
  ['rangeToNumber', (f) => f.helpers.rangeToNumber({ min: 1, max: 100 })],
  ['slugify', (f) => [' Hello World! ', 'Ça va très bien', 'über_cool-ness.txt', 'a/b\\c', 'ﬁne', 'Ærøskøbing'].map((s) => f.helpers.slugify(s))],
  ['replaceSymbols', (f) => f.helpers.replaceSymbols('#?*#?*-##??**')],
  ['replaceCreditCardSymbols', (f) => f.helpers.replaceCreditCardSymbols()],
  ['replaceCreditCardSymbols/pat', (f) => f.helpers.replaceCreditCardSymbols('1234-[4-9]-##!!-L')],
  ['replaceCreditCardSymbols/sym', (f) => f.helpers.replaceCreditCardSymbols('6011-*{4}-****-***L', '*')],
  ['fromRegExp/1', (f) => f.helpers.fromRegExp('#{5}')],
  ['fromRegExp/2', (f) => f.helpers.fromRegExp('#{2,9}')],
  ['fromRegExp/3', (f) => f.helpers.fromRegExp('[1-7]')],
  ['fromRegExp/4', (f) => f.helpers.fromRegExp('#{3}test[1-5]')],
  ['fromRegExp/5', (f) => f.helpers.fromRegExp('[0-9]{3}-[A-Z]{2,4}-.{5}')],
  ['fromRegExp/6', (f) => f.helpers.fromRegExp(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/)],
  ['fromRegExp/7', (f) => f.helpers.fromRegExp(/^[a-z]{3}$/i)],
  ['fromRegExp/8', (f) => f.helpers.fromRegExp(/x?y*z+/)],
  ['fromRegExp/9', (f) => f.helpers.fromRegExp(/[^a-z]{4}/)],
  ['fromRegExp/10', (f) => f.helpers.fromRegExp(/a.b.c/i)],
  ['fromRegExp/11', (f) => f.helpers.fromRegExp('[-a-c]{6}')],
  ['fromRegExp/12', (f) => f.helpers.fromRegExp(/q/i)],
  ['fromRegExp/13', (f) => f.helpers.fromRegExp('.')],
  ['fromRegExp/14', (f) => f.helpers.fromRegExp(/[a-f0-9]{8}-[^0-9]{2}/i)],
  ['mustache', (f) => f.helpers.mustache('I found {{count}} instances of "{{word}}".', { count: () => `${f.number.int(9)}`, word: 'th$is' })],
  ['fake/literal', (f) => f.helpers.fake('no tokens here')],
  ['fake/number', (f) => f.helpers.fake('{{number.int}} and {{number.int(5)}} and {{number.int({"min":10,"max":20})}}')],
  ['fake/string', (f) => f.helpers.fake('{{string.alpha(5)}}-{{string.numeric({"length":3})}}-{{string.uuid}}')],
  ['fake/helpers', (f) => f.helpers.fake('{{helpers.arrayElement(["a","b","c"])}}{{helpers.fromRegExp(X{3})}}')],
  ['fake/array', (f) => f.helpers.fake(['{{number.int(9)}}', 'x{{datatype.boolean}}'])],
  ['fake/registry', (f) => f.helpers.fake('{{number.bigInt}} {{number.bigInt(10)}} {{number.bigInt({"min":5,"max":9})}} {{helpers.objectEntry({"a":1,"b":2})}} {{helpers.enumValue({"A":"x","B":"y"})}}')],
  ['fake/unresolvable', (f) => f.helpers.fake('{{foo.bar}}')],
];
