const NAMES = [
  ['ascii', 'Jane', 'Doe'],
  ['apos', "D'Angelo", "O'Brien"],
  ['space', 'Mary Ann', 'Van der Berg'],
  ['accent', 'Jürgen', 'Müller-Lüdenscheidt'],
  ['cyrillic', 'Пётр', 'Иванов'],
  ['greek', 'Άλκηστις', 'Παπαδοπούλου'],
  ['cjk', '王', '小明'],
  ['kana', 'さくら', 'ﾔﾏﾀﾞ'],
  ['korean', '김', '민준'],
  ['arabic', 'آدم', 'إبراهيم'],
  ['hebrew', 'דוד', 'כֹּהֵן'],
  ['armenian', 'Արամ', 'Պետրոսյան'],
  ['emoji', 'A😀', '𝐁𝐨𝐛'],
  ['specialchars', 'a!b#c$d', '..x..y..'],
  ['long', 'Bartholomew-Maximilian-Alexander', 'Wolfeschlegelsteinhausenbergerdorff'],
  ['ligature', 'ﬁona', 'Ⅻ①'],
];

export const cases = [
  ['email', (f) => f.internet.email()],
  ['email/first', (f) => f.internet.email({ firstName: 'Jane' })],
  ['email/last', (f) => f.internet.email({ lastName: 'Doe' })],
  ['email/provider', (f) => f.internet.email({ provider: 'example.fakerjs.dev' })],
  ['email/special', (f) => f.internet.email({ allowSpecialCharacters: true })],
  ['email/special-names', (f) => f.internet.email({ firstName: 'Jane', lastName: 'Doe', allowSpecialCharacters: true })],
  ['email/dots', (f) => f.internet.email({ firstName: '.Jane.', lastName: '.' })],
  ['email/emptylast', (f) => f.internet.email({ firstName: 'Jane', lastName: '' })],
  ['exampleEmail', (f) => f.internet.exampleEmail()],
  ['exampleEmail/names', (f) => f.internet.exampleEmail({ firstName: 'Jane', lastName: 'Doe' })],
  ['exampleEmail/special', (f) => f.internet.exampleEmail({ allowSpecialCharacters: true })],
  ['username', (f) => f.internet.username()],
  ['username/first', (f) => f.internet.username({ firstName: 'Jane' })],
  ['username/last', (f) => f.internet.username({ lastName: 'Doe' })],
  ['username/emptylast', (f) => f.internet.username({ firstName: 'Jane', lastName: '' })],
  ['displayName', (f) => f.internet.displayName()],
  ['displayName/first', (f) => f.internet.displayName({ firstName: 'Jane' })],
  ['displayName/last', (f) => f.internet.displayName({ lastName: 'Doe' })],
  ['protocol', (f) => f.internet.protocol()],
  ['httpMethod', (f) => f.internet.httpMethod()],
  ['httpStatusCode', (f) => f.internet.httpStatusCode()],
  ['httpStatusCode/success', (f) => f.internet.httpStatusCode({ types: ['success'] })],
  ['httpStatusCode/errors', (f) => f.internet.httpStatusCode({ types: ['clientError', 'serverError'] })],
  ['httpStatusCode/all', (f) => f.internet.httpStatusCode({ types: ['informational', 'success', 'clientError', 'serverError', 'redirection'] })],
  ['httpStatusCode/empty', (f) => f.internet.httpStatusCode({ types: [] })],
  ['url', (f) => f.internet.url()],
  ['url/slash', (f) => f.internet.url({ appendSlash: true })],
  ['url/noslash', (f) => f.internet.url({ appendSlash: false })],
  ['url/http', (f) => f.internet.url({ protocol: 'http' })],
  ['url/https', (f) => f.internet.url({ protocol: 'https', appendSlash: true })],
  ['domainName', (f) => f.internet.domainName()],
  ['domainSuffix', (f) => f.internet.domainSuffix()],
  ['domainWord', (f) => f.internet.domainWord()],
  ['ip', (f) => f.internet.ip()],
  ['ipv4', (f) => f.internet.ipv4()],
  ...['any', 'loopback', 'private-a', 'private-b', 'private-c', 'test-net-1', 'test-net-2', 'test-net-3', 'link-local', 'multicast'].map((n) => [`ipv4/${n}`, (f) => f.internet.ipv4({ network: n })]),
  ...[
    '192.168.1.0/24', '10.0.0.1/32', '010.0.0.1/32', '0.0.0.0/0', '255.255.255.255/31', '255.255.255.255/1',
    '128.0.0.0/1', '172.31.255.7/30', '1.2.3.4/9',
    'abc', '1.2.3.4/33', '1.2.3.4/99', '256.0.0.0/8', '1.2.3/8', '1.2.3.4', '1.2.3.4/', '1.2.3.4/123', '1234.0.0.0/8', ' 1.2.3.4/8', '1.2.3.4/8 ',
  ].map((c) => [`ipv4/cidr:${c}`, (f) => f.internet.ipv4({ cidrBlock: c })]),
  ['ipv4/both', (f) => f.internet.ipv4({ cidrBlock: '192.0.2.0/30', network: 'loopback' })],
  ['ipv6', (f) => f.internet.ipv6()],
  ['port', (f) => f.internet.port()],
  ['userAgent', (f) => f.internet.userAgent()],
  ['mac', (f) => f.internet.mac()],
  ['mac/dash', (f) => f.internet.mac('-')],
  ['mac/empty', (f) => f.internet.mac('')],
  ['mac/invalid', (f) => f.internet.mac('|')],
  ['mac/obj', (f) => f.internet.mac({ separator: '-' })],
  ['mac/objdefault', (f) => f.internet.mac({})],
  ['password', (f) => f.internet.password()],
  ['password/5', (f) => f.internet.password({ length: 5 })],
  ['password/0', (f) => f.internet.password({ length: 0 })],
  ['password/memorable', (f) => f.internet.password({ memorable: true })],
  ['password/memorable20', (f) => f.internet.password({ length: 20, memorable: true })],
  ['password/upper', (f) => f.internet.password({ pattern: /[A-Z]/ })],
  ['password/digit', (f) => f.internet.password({ length: 8, pattern: /\d/ })],
  ['password/symbols', (f) => f.internet.password({ length: 12, pattern: /[^A-Za-z0-9]/ })],
  ['password/prefix', (f) => f.internet.password({ prefix: 'pre-' })],
  ['password/longprefix', (f) => f.internet.password({ length: 5, prefix: 'abcdefghij' })],
  ['password/memorableprefix', (f) => f.internet.password({ length: 10, memorable: true, prefix: 'xyz' })],
  ['password/memorablevowel', (f) => f.internet.password({ length: 10, memorable: true, prefix: 'Ba' })],
  ['password/memorablepattern', (f) => f.internet.password({ length: 10, memorable: true, pattern: /\d/ })],
  ['password/unicodeprefix', (f) => f.internet.password({ length: 10, prefix: 'é😀' })],
  ['emoji', (f) => f.internet.emoji()],
  ['emoji/flag', (f) => f.internet.emoji({ types: ['flag'] })],
  ['emoji/foodnature', (f) => f.internet.emoji({ types: ['food', 'nature'] })],
  ['emoji/empty', (f) => f.internet.emoji({ types: [] })],
  ['jwtAlgorithm', (f) => f.internet.jwtAlgorithm()],
  ['jwt', (f) => f.internet.jwt()],
  ['jwt/ref', (f) => f.internet.jwt({ refDate: '2020-01-01T00:00:00.000Z' })],
  ['jwt/refnum', (f) => f.internet.jwt({ refDate: 1600000000123 })],
  ['jwt/referr', (f) => f.internet.jwt({ refDate: NaN })],
  ['jwt/header', (f) => f.internet.jwt({ header: { alg: 'none', kid: 'ключ', n: 1.5, b: true, z: null, a: [1, 'x'] } })],
  ['jwt/payload', (f) => f.internet.jwt({ payload: { sub: 'abc', admin: true, nested: { x: 'é\n"' } } })],
  ['jwt/both', (f) => f.internet.jwt({ header: {}, payload: {} })],
  ['fake/misc', (f) => f.helpers.fake('{{internet.email}}|{{internet.exampleEmail}}|{{internet.username}}|{{internet.displayName}}|{{internet.protocol}}|{{internet.httpMethod}}|{{internet.httpStatusCode}}|{{internet.url}}|{{internet.domainName}}|{{internet.domainSuffix}}|{{internet.domainWord}}|{{internet.ip}}|{{internet.ipv4}}|{{internet.ipv6}}|{{internet.port}}|{{internet.mac}}|{{internet.password}}|{{internet.emoji}}|{{internet.jwtAlgorithm}}')],
  ['fake/userAgent', (f) => f.helpers.fake('{{internet.userAgent}}')],
  ['fake/jwt', (f) => f.helpers.fake('{{internet.jwt}}')],
  ['fake/args', (f) => f.helpers.fake('{{internet.email({"firstName":"Jane","provider":"x.dev","allowSpecialCharacters":true})}}|{{internet.username({"lastName":"Doe"})}}|{{internet.displayName({"firstName":"Jo"})}}|{{internet.httpStatusCode({"types":["success"]})}}|{{internet.url({"appendSlash":true,"protocol":"http"})}}|{{internet.ipv4({"network":"private-c"})}}|{{internet.ipv4({"cidrBlock":"10.1.0.0/16"})}}|{{internet.mac("-")}}|{{internet.mac({"separator":""})}}|{{internet.password({"length":6,"memorable":true})}}|{{internet.emoji({"types":["flag"]})}}')],
  ['fake/jwtargs', (f) => f.helpers.fake('{{internet.jwt({"header":{"alg":"x"},"refDate":"2020-01-01T00:00:00.000Z"})}}')],
  ['fake/ipv4bad', (f) => f.helpers.fake('{{internet.ipv4({"network":"bogus"})}}')],
];

for (const [id, first, last] of NAMES) {
  cases.push(
    [`username/${id}`, (f) => f.internet.username({ firstName: first, lastName: last })],
    [`username/${id}/first`, (f) => f.internet.username({ firstName: first + last })],
    [`email/${id}`, (f) => f.internet.email({ firstName: first, lastName: last })],
    [`displayName/${id}`, (f) => f.internet.displayName({ firstName: first, lastName: last })],
  );
}
