export const cases = [
  ['fileName', (f) => f.system.fileName()],
  ['fileName/0', (f) => f.system.fileName({ extensionCount: 0 })],
  ['fileName/3', (f) => f.system.fileName({ extensionCount: 3 })],
  ['fileName/range', (f) => f.system.fileName({ extensionCount: { min: 1, max: 4 } })],
  ['fileName/range0', (f) => f.system.fileName({ extensionCount: { min: 0, max: 2 } })],
  ['commonFileName', (f) => f.system.commonFileName()],
  ['commonFileName/ext', (f) => f.system.commonFileName('txt')],
  ['commonFileName/empty', (f) => f.system.commonFileName('')],
  ['mimeType', (f) => f.system.mimeType()],
  ['commonFileType', (f) => f.system.commonFileType()],
  ['commonFileExt', (f) => f.system.commonFileExt()],
  ['fileType', (f) => f.system.fileType()],
  ['fileExt', (f) => f.system.fileExt()],
  ['fileExt/png', (f) => f.system.fileExt('image/png')],
  ['fileExt/jpeg', (f) => f.system.fileExt('image/jpeg')],
  ['fileExt/mpeg', (f) => f.system.fileExt('audio/mpeg')],
  ['fileExt/err', (f) => f.system.fileExt('foo/bar')],
  ['fileExt/errempty', (f) => f.system.fileExt('')],
  ['directoryPath', (f) => f.system.directoryPath()],
  ['filePath', (f) => f.system.filePath()],
  ['semver', (f) => f.system.semver()],
  ['networkInterface', (f) => f.system.networkInterface()],
  ...['en', 'wl', 'ww'].map((t) => [`networkInterface/type:${t}`, (f) => f.system.networkInterface({ interfaceType: t })]),
  ...['index', 'slot', 'mac', 'pci'].map((s) => [`networkInterface/schema:${s}`, (f) => f.system.networkInterface({ interfaceSchema: s })]),
  ['networkInterface/both', (f) => f.system.networkInterface({ interfaceType: 'wl', interfaceSchema: 'pci' })],
  ['cron', (f) => f.system.cron()],
  ['cron/year', (f) => f.system.cron({ includeYear: true })],
  ['cron/nonstandard', (f) => f.system.cron({ includeNonStandard: true })],
  ['cron/both', (f) => f.system.cron({ includeYear: true, includeNonStandard: true })],
  ['cron/false', (f) => f.system.cron({ includeYear: false, includeNonStandard: false })],
  ['fake/misc', (f) => f.helpers.fake('{{system.fileName}}|{{system.commonFileName}}|{{system.mimeType}}|{{system.commonFileType}}|{{system.commonFileExt}}|{{system.fileType}}|{{system.fileExt}}|{{system.directoryPath}}|{{system.filePath}}|{{system.semver}}|{{system.networkInterface}}|{{system.cron}}')],
  ['fake/args', (f) => f.helpers.fake('{{system.fileName({"extensionCount":2})}}|{{system.commonFileName("pdf")}}|{{system.fileExt("image/gif")}}|{{system.networkInterface({"interfaceType":"ww","interfaceSchema":"slot"})}}|{{system.cron({"includeYear":true,"includeNonStandard":true})}}')],
  ['fake/fileExtErr', (f) => f.helpers.fake('{{system.fileExt("nope/nope")}}')],
];
