(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [eo] locale (Esperanto). Fallback chain: eo -> en -> base. *)

let def = lazy (Json.parse Eo_data.json)

(** The raw [eo] definitions, like faker-js [eo]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: eo, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [eo] instance (random seed), like faker-js [fakerEO]. *)
let faker () = Lazy.force instance
