(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [en_CA] locale (English (Canada)). Fallback chain: en_CA -> en -> base. *)

let def = lazy (Json.parse En_CA_data.json)

(** The raw [en_CA] definitions, like faker-js [en_CA]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: en_CA, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [en_CA] instance (random seed), like faker-js [fakerEN_CA]. *)
let faker () = Lazy.force instance
