(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [es] locale (Spanish). Fallback chain: es -> en -> base. *)

let def = lazy (Json.parse Es_data.json)

(** The raw [es] definitions, like faker-js [es]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: es, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [es] instance (random seed), like faker-js [fakerES]. *)
let faker () = Lazy.force instance
