(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [zu_ZA] locale (Zulu (South Africa)). Fallback chain: zu_ZA -> en -> base. *)

let def = lazy (Json.parse Zu_ZA_data.json)

(** The raw [zu_ZA] definitions, like faker-js [zu_ZA]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: zu_ZA, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [zu_ZA] instance (random seed), like faker-js [fakerZU_ZA]. *)
let faker () = Lazy.force instance
