(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [pl] locale (Polish). Fallback chain: pl -> en -> base. *)

let def = lazy (Json.parse Pl_data.json)

(** The raw [pl] definitions, like faker-js [pl]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: pl, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [pl] instance (random seed), like faker-js [fakerPL]. *)
let faker () = Lazy.force instance
