(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [it] locale (Italian). Fallback chain: it -> en -> base. *)

let def = lazy (Json.parse It_data.json)

(** The raw [it] definitions, like faker-js [it]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: it, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [it] instance (random seed), like faker-js [fakerIT]. *)
let faker () = Lazy.force instance
