(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [da] locale (Danish). Fallback chain: da -> en -> base. *)

let def = lazy (Json.parse Da_data.json)

(** The raw [da] definitions, like faker-js [da]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: da, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [da] instance (random seed), like faker-js [fakerDA]. *)
let faker () = Lazy.force instance
