(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [sr_RS_latin] locale (Serbian (Serbia, Latin)). Fallback chain:
    sr_RS_latin -> en -> base. *)

let def = lazy (Json.parse Sr_RS_latin_data.json)

(** The raw [sr_RS_latin] definitions, like faker-js [sr_RS_latin]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: sr_RS_latin, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [sr_RS_latin] instance (random seed), like faker-js
    [fakerSR_RS_latin]. *)
let faker () = Lazy.force instance
