(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [he] locale (Hebrew). Fallback chain: he -> en -> base. *)

let def = lazy (Json.parse He_data.json)

(** The raw [he] definitions, like faker-js [he]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: he, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [he] instance (random seed), like faker-js [fakerHE]. *)
let faker () = Lazy.force instance
