(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [de] locale (German). Fallback chain: de -> en -> base. *)

let def = lazy (Json.parse De_data.json)

(** The raw [de] definitions, like faker-js [de]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: de, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [de] instance (random seed), like faker-js [fakerDE]. *)
let faker () = Lazy.force instance
