(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [en_AU] locale (English (Australia)). Fallback chain: en_AU -> en ->
    base. *)

let def = lazy (Json.parse En_AU_data.json)

(** The raw [en_AU] definitions, like faker-js [en_AU]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: en_AU, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [en_AU] instance (random seed), like faker-js [fakerEN_AU]. *)
let faker () = Lazy.force instance
