(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [yo_NG] locale (Yoruba (Nigeria)). Fallback chain: yo_NG -> en -> base. *)

let def = lazy (Json.parse Yo_NG_data.json)

(** The raw [yo_NG] definitions, like faker-js [yo_NG]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: yo_NG, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [yo_NG] instance (random seed), like faker-js [fakerYO_NG]. *)
let faker () = Lazy.force instance
