(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [en_AU_ocker] locale (English (Australia Ocker)). Fallback chain:
    en_AU_ocker -> en_AU -> en -> base. *)

let def = lazy (Json.parse En_AU_ocker_data.json)

(** The raw [en_AU_ocker] definitions, like faker-js [en_AU_ocker]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: en_AU_ocker, en_AU, en, base.
*)
let chain () =
  [
    definition ();
    Locale_en_AU.definition ();
    Locale_en.definition ();
    Locale_base.definition ();
  ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [en_AU_ocker] instance (random seed), like faker-js
    [fakerEN_AU_ocker]. *)
let faker () = Lazy.force instance
