(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [ku_kmr_latin] locale (Kurdish (Kurmanji, Latin)). Fallback chain:
    ku_kmr_latin -> en -> base. *)

let def = lazy (Json.parse Ku_kmr_latin_data.json)

(** The raw [ku_kmr_latin] definitions, like faker-js [ku_kmr_latin]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: ku_kmr_latin, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [ku_kmr_latin] instance (random seed), like faker-js
    [fakerKU_kmr_latin]. *)
let faker () = Lazy.force instance
