(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [fr_LU] locale (French (Luxembourg)). Fallback chain: fr_LU -> fr -> en
    -> base. *)

let def = lazy (Json.parse Fr_LU_data.json)

(** The raw [fr_LU] definitions, like faker-js [fr_LU]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: fr_LU, fr, en, base. *)
let chain () =
  [
    definition ();
    Locale_fr.definition ();
    Locale_en.definition ();
    Locale_base.definition ();
  ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [fr_LU] instance (random seed), like faker-js [fakerFR_LU]. *)
let faker () = Lazy.force instance
