(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [ar] locale (Arabic). Fallback chain: ar -> en -> base. *)

let def = lazy (Json.parse Ar_data.json)

(** The raw [ar] definitions, like faker-js [ar]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: ar, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [ar] instance (random seed), like faker-js [fakerAR]. *)
let faker () = Lazy.force instance
