(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [tr] locale (Turkish). Fallback chain: tr -> en -> base. *)

let def = lazy (Json.parse Tr_data.json)

(** The raw [tr] definitions, like faker-js [tr]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: tr, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [tr] instance (random seed), like faker-js [fakerTR]. *)
let faker () = Lazy.force instance
