(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [en_US] locale (English (United States)). Fallback chain: en_US -> en ->
    base. *)

let def = lazy (Json.parse En_US_data.json)

(** The raw [en_US] definitions, like faker-js [en_US]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: en_US, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [en_US] instance (random seed), like faker-js [fakerEN_US]. *)
let faker () = Lazy.force instance
