(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [lv] locale (Latvian). Fallback chain: lv -> en -> base. *)

let def = lazy (Json.parse Lv_data.json)

(** The raw [lv] definitions, like faker-js [lv]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: lv, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [lv] instance (random seed), like faker-js [fakerLV]. *)
let faker () = Lazy.force instance
