(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [de_AT] locale (German (Austria)). Fallback chain: de_AT -> de -> en -> base. *)

let def = lazy (Json.parse De_AT_data.json)

(** The raw [de_AT] definitions, like faker-js [de_AT]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: de_AT, de, en, base. *)
let chain () = [ definition (); Locale_de.definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [de_AT] instance (random seed), like faker-js [fakerDE_AT]. *)
let faker () = Lazy.force instance
