(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [ja] locale (Japanese). Fallback chain: ja -> en -> base. *)

let def = lazy (Json.parse Ja_data.json)

(** The raw [ja] definitions, like faker-js [ja]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: ja, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [ja] instance (random seed), like faker-js [fakerJA]. *)
let faker () = Lazy.force instance
