(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [hr] locale (Croatian). Fallback chain: hr -> en -> base. *)

let def = lazy (Json.parse Hr_data.json)

(** The raw [hr] definitions, like faker-js [hr]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: hr, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [hr] instance (random seed), like faker-js [fakerHR]. *)
let faker () = Lazy.force instance
