(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [fa] locale (Farsi/Persian). Fallback chain: fa -> en -> base. *)

let def = lazy (Json.parse Fa_data.json)

(** The raw [fa] definitions, like faker-js [fa]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: fa, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [fa] instance (random seed), like faker-js [fakerFA]. *)
let faker () = Lazy.force instance
