(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [sk] locale (Slovak). Fallback chain: sk -> en -> base. *)

let def = lazy (Json.parse Sk_data.json)

(** The raw [sk] definitions, like faker-js [sk]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: sk, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [sk] instance (random seed), like faker-js [fakerSK]. *)
let faker () = Lazy.force instance
