(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [mn_MN_cyrl] locale (Mongolian (Mongolia, Cyrillic)). Fallback chain:
    mn_MN_cyrl -> en -> base. *)

let def = lazy (Json.parse Mn_MN_cyrl_data.json)

(** The raw [mn_MN_cyrl] definitions, like faker-js [mn_MN_cyrl]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: mn_MN_cyrl, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [mn_MN_cyrl] instance (random seed), like faker-js
    [fakerMN_MN_cyrl]. *)
let faker () = Lazy.force instance
