(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [fr_BE] locale (French (Belgium)). Fallback chain: fr_BE -> fr -> en ->
    base. *)

let def = lazy (Json.parse Fr_BE_data.json)

(** The raw [fr_BE] definitions, like faker-js [fr_BE]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: fr_BE, fr, en, base. *)
let chain () =
  [
    definition ();
    Locale_fr.definition ();
    Locale_en.definition ();
    Locale_base.definition ();
  ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [fr_BE] instance (random seed), like faker-js [fakerFR_BE]. *)
let faker () = Lazy.force instance
