(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [zh_TW] locale (Chinese (Taiwan)). Fallback chain: zh_TW -> en -> base.
*)

let def = lazy (Json.parse Zh_TW_data.json)

(** The raw [zh_TW] definitions, like faker-js [zh_TW]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: zh_TW, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [zh_TW] instance (random seed), like faker-js [fakerZH_TW]. *)
let faker () = Lazy.force instance
