(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [sv] locale (Swedish). Fallback chain: sv -> en -> base. *)

let def = lazy (Json.parse Sv_data.json)

(** The raw [sv] definitions, like faker-js [sv]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: sv, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [sv] instance (random seed), like faker-js [fakerSV]. *)
let faker () = Lazy.force instance
