(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [zh_CN] locale (Chinese (China)). Fallback chain: zh_CN -> en -> base. *)

let def = lazy (Json.parse Zh_CN_data.json)

(** The raw [zh_CN] definitions, like faker-js [zh_CN]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: zh_CN, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [zh_CN] instance (random seed), like faker-js [fakerZH_CN]. *)
let faker () = Lazy.force instance
