(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [en_NP] locale (English (Nepal)). Fallback chain: en_NP -> en -> base.
*)

let def = lazy (Json.parse En_NP_data.json)

(** The raw [en_NP] definitions, like faker-js [en_NP]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: en_NP, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [en_NP] instance (random seed), like faker-js [fakerEN_NP]. *)
let faker () = Lazy.force instance
