(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [id_ID] locale (Indonesian (Indonesia)). Fallback chain: id_ID -> en -> base. *)

let def = lazy (Json.parse Id_ID_data.json)

(** The raw [id_ID] definitions, like faker-js [id_ID]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: id_ID, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [id_ID] instance (random seed), like faker-js [fakerID_ID]. *)
let faker () = Lazy.force instance
