(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [en_ZA] locale (English (South Africa)). Fallback chain: en_ZA -> en ->
    base. *)

let def = lazy (Json.parse En_ZA_data.json)

(** The raw [en_ZA] definitions, like faker-js [en_ZA]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: en_ZA, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [en_ZA] instance (random seed), like faker-js [fakerEN_ZA]. *)
let faker () = Lazy.force instance
