(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [hu] locale (Hungarian). Fallback chain: hu -> en -> base. *)

let def = lazy (Json.parse Hu_data.json)

(** The raw [hu] definitions, like faker-js [hu]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: hu, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [hu] instance (random seed), like faker-js [fakerHU]. *)
let faker () = Lazy.force instance
