(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [ta_IN] locale (Tamil (India)). Fallback chain: ta_IN -> en -> base. *)

let def = lazy (Json.parse Ta_IN_data.json)

(** The raw [ta_IN] definitions, like faker-js [ta_IN]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: ta_IN, en, base. *)
let chain () = [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [ta_IN] instance (random seed), like faker-js [fakerTA_IN]. *)
let faker () = Lazy.force instance
