(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)

(** The [fi] locale (Finnish). Fallback chain: fi -> en -> base. *)

let def = lazy (Json.parse Fi_data.json)

(** The raw [fi] definitions, like faker-js [fi]. *)
let definition () = Lazy.force def

(** The locale chain the prebuilt instance uses: fi, en, base. *)
let chain () =
  [ definition (); Locale_en.definition (); Locale_base.definition () ]

let instance = lazy (Core.create ~locale:(chain ()) ())

(** The shared [fi] instance (random seed), like faker-js [fakerFI]. *)
let faker () = Lazy.force instance
