// Runs every case in tools/cases/*.mjs against faker-js and writes the expected
// results to test/expected/<group>.ml.
//
// A case file exports `cases`: an array of { id, run(faker) } (or `[id, run]`).
// Each case is run with each seed on a fresh Faker({ locale: [en, base] }) whose
// default reference date is REF_DATE; `run` is called RUNS times and the results
// are JSON-encoded (Dates as ISO strings, bigints as strings, undefined as null).
//
// Usage: node tools/gen_fixtures.mjs [group ...]
import { readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { Faker, en, base } from '@faker-js/faker';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const casesDir = join(root, 'tools', 'cases');
export const SEEDS = process.env.FIXTURE_SEEDS
  ? Array.from({ length: Number(process.env.FIXTURE_SEEDS) }, (_, i) => i * 7919 + 1)
  : [42, 1337, 7];
export const RUNS = 3;
export const REF_DATE = '2025-01-01T00:00:00.000Z';

const replacer = (_k, v) => (typeof v === 'bigint' ? v.toString() : v === undefined ? null : v);
const encode = (v) => JSON.stringify(v === undefined ? null : v, replacer);

const only = process.argv.slice(2);
const files = readdirSync(casesDir).filter((f) => f.endsWith('.mjs'));

for (const file of files) {
  const group = file.replace(/\.mjs$/, '');
  if (only.length && !only.includes(group)) continue;
  const mod = await import(pathToFileURL(join(casesDir, file)));
  const seeds = mod.seeds ?? SEEDS;
  // FIXTURE_SEEDS=n regenerates with n seeds for a wider (temporary) parity sweep.
  const runs = mod.runs ?? RUNS;
  const rows = [];
  const seen = new Set();
  for (const c of mod.cases) {
    const [id, run] = Array.isArray(c) ? c : [c.id, c.run];
    if (seen.has(id)) throw new Error(`duplicate case id ${group}/${id}`);
    seen.add(id);
    for (const seed of seeds) {
      const faker = new Faker({ locale: [en, base], seed });
      faker.setDefaultRefDate(REF_DATE);
      const results = [];
      for (let i = 0; i < runs; i++) {
        let r;
        try {
          r = run(faker);
        } catch (e) {
          r = { error: e.message };
        }
        results.push(r);
      }
      rows.push([id, seed, `[${results.map(encode).join(',')}]`]);
    }
  }
  const delim = (s) => {
    let d = 'x';
    while (s.includes(`|${d}}`)) d += 'x';
    return `{${d}|${s}|${d}}`;
  };
  const out =
    `(* GENERATED by tools/gen_fixtures.mjs from tools/cases/${file} - do not edit. *)\n\n` +
    `let cases = [\n` +
    rows.map(([id, seed, json]) => `  (${JSON.stringify(id)}, ${seed}, ${delim(json)});\n`).join('') +
    `]\n`;
  writeFileSync(join(root, 'test', 'expected', `expected_${group}.ml`), out);
  console.log(`${group}: ${rows.length} rows`);
}
