// Generates lib/internal/unicode_table.ml: for code points whose NFKD form differs,
// the NFKD decomposition (as UTF-8). Covers the Latin, Greek, Cyrillic and
// compatibility blocks relevant to slugify()/internet usernames.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ranges = [[0x80, 0x52f], [0x1e00, 0x1fff], [0x2000, 0x218f], [0x2460, 0x24ff], [0x3000, 0x30ff], [0xfb00, 0xfb4f], [0xff00, 0xffef]];
const rows = [];
for (const [a, b] of ranges)
  for (let cp = a; cp <= b; cp++) {
    const s = String.fromCodePoint(cp);
    const d = s.normalize('NFKD');
    if (d !== s) rows.push(`  (0x${cp.toString(16)}, ${JSON.stringify(d).replace(/\\u([0-9a-f]{4})/g, (_, h) => `\\u{${h}}`)});`);
  }
writeFileSync(join(root, 'lib', 'internal', 'unicode_table.ml'),
  `(* GENERATED by tools/gen_unicode.mjs - do not edit. NFKD decompositions. *)\n\nlet nfkd = [|\n${rows.join('\n')}\n|]\n`);
console.log(rows.length);
