// Generates lib/locales/<name>_data.ml from the @faker-js/faker locale definitions.
// Usage: node tools/gen_locale.mjs [locale ...]   (default: en base)
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as faker from '@faker-js/faker';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const names = process.argv.slice(2).length ? process.argv.slice(2) : ['en', 'base'];
const DELIM = 'fakerjson';

for (const name of names) {
  const def = faker.allLocales[name];
  if (!def) throw new Error(`Unknown locale ${name}`);
  const json = JSON.stringify(def);
  if (json.includes(`|${DELIM}}`)) throw new Error('delimiter collision');
  const out =
    `(* GENERATED by tools/gen_locale.mjs from @faker-js/faker 10.6.0 - do not edit. *)\n\n` +
    `let json = {${DELIM}|${json}|${DELIM}}\n`;
  writeFileSync(join(root, 'lib', 'locales', `${name}_data.ml`), out);
  console.log(`wrote ${name}_data.ml (${json.length} bytes)`);
}
