(* GENERATED by tools/gen_fixtures.mjs from tools/cases/l10n.mjs - do not edit. *)

let locale = "da"

let cases =
  [
    ("person.firstName(\"female\")", 42, {x|["Helene","Tine"]|x});
    ("person.firstName(\"female\")", 1337, {x|["Ellen-Margrethe","Cecilie"]|x});
    ("person.firstName(\"female\")", 7, {x|["Anne","Rebecca"]|x});
    ("person.firstName(\"male\")", 42, {x|["Johan","Viggo"]|x});
    ("person.firstName(\"male\")", 1337, {x|["Frederik","Christian"]|x});
    ("person.firstName(\"male\")", 7, {x|["Andreas","Samuel"]|x});
    ("person.lastName(\"female\")", 42, {x|["Thomsen","Knudsen"]|x});
    ("person.lastName(\"female\")", 1337, {x|["Bruun","Jakobsen"]|x});
    ("person.lastName(\"female\")", 7, {x|["Olsen","Munk"]|x});
    ("person.lastName(\"male\")", 42, {x|["Thomsen","Knudsen"]|x});
    ("person.lastName(\"male\")", 1337, {x|["Bruun","Jakobsen"]|x});
    ("person.lastName(\"male\")", 7, {x|["Olsen","Munk"]|x});
    ("person.middleName(\"female\")", 42, {x|["Hjorth","Vestergaard"]|x});
    ("person.middleName(\"female\")", 1337, {x|["Feldt","Dahl"]|x});
    ("person.middleName(\"female\")", 7, {x|["Bjerre","Nord"]|x});
    ( "person.fullName({\"sex\":\"female\"})",
      42,
      {x|["Helene Møller-Knudsen","Cecilie Mose Schmidt"]|x} );
    ( "person.fullName({\"sex\":\"female\"})",
      1337,
      {x|["Ellen-Margrethe Dupont","Freja Mose Damm"]|x} );
    ( "person.fullName({\"sex\":\"female\"})",
      7,
      {x|["Anne Østergaard Holm","Lene Beckmann"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      42,
      {x|["Johan Møller-Knudsen","Christian Mose Schmidt"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      1337,
      {x|["Frederik Dupont","Ivan Mose Damm"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      7,
      {x|["Andreas Østergaard Holm","Lukas Beckmann"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      42,
      {x|["Anna Møller-Knudsen","Anna Mose Schmidt"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      1337,
      {x|["Anna Dupont","Anna Mose Damm"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      7,
      {x|["Anna Østergaard Holm","Anna Beckmann"]|x} );
    ("person.prefix(\"female\")", 42, {x|["fr.","fr."]|x});
    ("person.prefix(\"female\")", 1337, {x|["fr.","fr."]|x});
    ("person.prefix(\"female\")", 7, {x|["fr.","fr."]|x});
    ("person.prefix(\"male\")", 42, {x|["hr.","hr."]|x});
    ("person.prefix(\"male\")", 1337, {x|["hr.","hr."]|x});
    ("person.prefix(\"male\")", 7, {x|["hr.","hr."]|x});
    ("person.suffix()", 42, {x|["III","DVM"]|x});
    ("person.suffix()", 1337, {x|["I","Sr."]|x});
    ("person.suffix()", 7, {x|["Jr.","DDS"]|x});
    ( "location.zipCode({\"state\":\"CA\"})",
      42,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      1337,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      7,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      42,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      1337,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      7,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ("location.zipCode(\"###\")", 42, {x|["397","511"]|x});
    ("location.zipCode(\"###\")", 1337, {x|["212","435"]|x});
    ("location.zipCode(\"###\")", 7, {x|["074","795"]|x});
    ("location.state({\"abbreviated\":true})", 42, {x|["ME","WV"]|x});
    ("location.state({\"abbreviated\":true})", 1337, {x|["IN","DE"]|x});
    ("location.state({\"abbreviated\":true})", 7, {x|["AR","RI"]|x});
    ( "location.streetAddress(true)",
      42,
      {x|["Jagtvej 75B, 2. tv","Bjergvej 67B, 9. tv"]|x} );
    ( "location.streetAddress(true)",
      1337,
      {x|["Galgebjergvej 3, 3. tv","Markvej 97, 4. tv"]|x} );
    ( "location.streetAddress(true)",
      7,
      {x|["Cedervej 47A, 5. th","Lyngvej 3, 7. tv"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      42,
      {x|["Jagtvej 75B, 2. tv","Bjergvej 67B, 9. tv"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      1337,
      {x|["Galgebjergvej 3, 3. tv","Markvej 97, 4. tv"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      7,
      {x|["Cedervej 47A, 5. th","Lyngvej 3, 7. tv"]|x} );
    ("location.countryCode(\"alpha-3\")", 42, {x|["GUY","VCT"]|x});
    ("location.countryCode(\"alpha-3\")", 1337, {x|["ESH","COD"]|x});
    ("location.countryCode(\"alpha-3\")", 7, {x|["BEL","SYC"]|x});
    ("location.countryCode(\"numeric\")", 42, {x|["328","670"]|x});
    ("location.countryCode(\"numeric\")", 1337, {x|["732","180"]|x});
    ("location.countryCode(\"numeric\")", 7, {x|["056","690"]|x});
    ( "location.timeZone()",
      42,
      {x|["America/North_Dakota/Center","Pacific/Kosrae"]|x} );
    ( "location.timeZone()",
      1337,
      {x|["America/Guadeloupe","America/Argentina/San_Luis"]|x} );
    ("location.timeZone()", 7, {x|["Africa/Libreville","Europe/Gibraltar"]|x});
    ("date.month({\"abbreviated\":true})", 42, {x|["jan.","sep."]|x});
    ("date.month({\"abbreviated\":true})", 1337, {x|["feb.","aug."]|x});
    ("date.month({\"abbreviated\":true})", 7, {x|["apr.","nov."]|x});
    ("date.month({\"context\":true})", 42, {x|["januar","september"]|x});
    ("date.month({\"context\":true})", 1337, {x|["februar","august"]|x});
    ("date.month({\"context\":true})", 7, {x|["april","november"]|x});
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      42,
      {x|["jan.","sep."]|x} );
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      1337,
      {x|["feb.","aug."]|x} );
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      7,
      {x|["apr.","nov."]|x} );
    ("date.weekday({\"abbreviated\":true})", 42, {x|["man.","tor."]|x});
    ("date.weekday({\"abbreviated\":true})", 1337, {x|["lør.","lør."]|x});
    ("date.weekday({\"abbreviated\":true})", 7, {x|["fre.","tir."]|x});
    ("date.weekday({\"context\":true})", 42, {x|["mandag","torsdag"]|x});
    ("date.weekday({\"context\":true})", 1337, {x|["lørdag","lørdag"]|x});
    ("date.weekday({\"context\":true})", 7, {x|["fredag","tirsdag"]|x});
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      42,
      {x|["man.","tor."]|x} );
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      1337,
      {x|["lør.","lør."]|x} );
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      7,
      {x|["fre.","tir."]|x} );
    ( "phone.number({\"style\":\"human\"})",
      42,
      {x|["97511086","+45 2982 1135"]|x} );
    ( "phone.number({\"style\":\"human\"})",
      1337,
      {x|["3243 5297","56 19 47 73"]|x} );
    ("phone.number({\"style\":\"human\"})", 7, {x|["84 79 55 02","78302924"]|x});
    ( "phone.number({\"style\":\"national\"})",
      42,
      {x|["49 75 11 08","67 09 82 11"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      1337,
      {x|["41 24 35 29","71 36 19 47"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      7,
      {x|["27 47 95 50","44 68 30 29"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      42,
      {x|["+4549751108","+4567098211"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      1337,
      {x|["+4541243529","+4571361947"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      7,
      {x|["+4527479550","+4544683029"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      42,
      {x|["ledig","vis"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      1337,
      {x|["hård","frodig"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      7,
      {x|["dyr","svag"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      42,
      {x|["kirke","værdi"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      1337,
      {x|["grund","farve"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      7,
      {x|["bjerg","rolle"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      42,
      {x|["få","se"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      1337,
      {x|["få","bo"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      7,
      {x|["bo","se"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      42,
      {x|["igen","fest"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      1337,
      {x|["hvem","mens"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      7,
      {x|["male","imod"]|x} );
    ( "word.words(5)",
      42,
      {x|["altid erhverv pyha nej som","ja nej varm om ved"]|x} );
    ( "word.words(5)",
      1337,
      {x|["end så svag efterår langs","overalt magasin aldrig acceptere udenfor"]|x}
    );
    ( "word.words(5)",
      7,
      {x|["lytte af oh spil hos","give fleksibel ah anmode lun"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      42,
      {x|["crux","vito"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      1337,
      {x|["ceno","arma"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      7,
      {x|["alii","tibi"]|x} );
    ( "lorem.sentences(3)",
      42,
      {x|["Virga synagoga patruus armarium armarium. Usitas paulatim suggero. Volubilis tristis benevolentia.","Auctus cognomen esse custodia. Perspiciatis apud claro copiose defleo. Aveho doloribus omnis adipiscor pectus assumenda advoco vinum vociferor."]|x}
    );
    ( "lorem.sentences(3)",
      1337,
      {x|["Articulus chirographum degenero commemoro eaque. Voluptatibus tabella ancilla creptio quisquam. Vorago decipio testimonium thalassinus.","Cupressus nulla temporibus audeo civis. Desidero atrox cupiditate avarus exercitationem tristis audax vita. Desparatus dolore accendo suus vulgo ascisco."]|x}
    );
    ( "lorem.sentences(3)",
      7,
      {x|["Termes debitis supra. Fugiat desino aequitas censura desidero spoliatio thymbra creator aedificium civis. Benigne defero vicinus acidus pauci virga callide infit verbera appello.","Tandem sortitus delibero bardus deprecator corroboro demoror. Tum tenuis combibo nam cetera. Conservo solum corpus degenero super cupiditate."]|x}
    );
    ( "lorem.paragraphs(2)",
      42,
      {x|["Virga synagoga patruus armarium armarium. Usitas paulatim suggero. Volubilis tristis benevolentia.\nAuctus cognomen esse custodia. Perspiciatis apud claro copiose defleo. Aveho doloribus omnis adipiscor pectus assumenda advoco vinum vociferor.","Cogo alter stella decerno animus deputo adeo verbera caute. Color eius incidunt audacia volubilis terga vigor varius. Verus alienus autus adipisci comparo creta cernuus.\nConsuasor cicuta illo aqua thorax aestas vos ter avarus. Tot suffragium suspendo. Aer contego ancilla urbanus qui comptus adversus colo communis."]|x}
    );
    ( "lorem.paragraphs(2)",
      1337,
      {x|["Articulus chirographum degenero commemoro eaque. Voluptatibus tabella ancilla creptio quisquam. Vorago decipio testimonium thalassinus.\nCupressus nulla temporibus audeo civis. Desidero atrox cupiditate avarus exercitationem tristis audax vita. Desparatus dolore accendo suus vulgo ascisco.","Corrupti suadeo abbas corporis. Testimonium consectetur subvenio. Voluptas tubineus pel magni vulpes caterva.\nAlienus vigor voluptate. Confugo supra abstergo temporibus speciosus aufero. Vere arx verbum communis subseco cena earum atrocitas."]|x}
    );
    ( "lorem.paragraphs(2)",
      7,
      {x|["Termes debitis supra. Fugiat desino aequitas censura desidero spoliatio thymbra creator aedificium civis. Benigne defero vicinus acidus pauci virga callide infit verbera appello.\nTandem sortitus delibero bardus deprecator corroboro demoror. Tum tenuis combibo nam cetera. Conservo solum corpus degenero super cupiditate.","Attollo talio curis curso reiciendis eos cuppedia ab aliquam sui. Subito vis statua adnuo colligo optio canonicus. Vinculum ubi demens turba aperte colligo delectatio talis depereo approbo.\nCommunis coerceo asperiores cuppedia dedico. Theca enim degusto tergo valens spero thesaurus vigor adhaero. Charisma demonstro theca sunt arceo soluta aegrus consuasor torqueo cursus."]|x}
    );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      42,
      {x|["Jurgen_60degard@hotmail.com","Jurgen.60degard@gmail.com"]|x} );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      1337,
      {x|["Jurgen.60degard27@hotmail.com","Jurgen_60degard@hotmail.com"]|x} );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      7,
      {x|["Jurgen_60degard@gmail.com","Jurgen_60degard50@yahoo.dk"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      42,
      {x|["Anna.8xukasz","Anna_8xukasz15"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      1337,
      {x|["Anna.8xukasz15","Anna.8xukasz"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      7,
      {x|["Anna.8xukasz77","Anna_8xukasz"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      42,
      {x|["Zoë15","Zoë.Munch96"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      1337,
      {x|["Zoë.Dupont","Zoë62"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      7,
      {x|["Zoë_Holm","Zoë.Davidsen67"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      42,
      {x|["Per.Bruun@hotmail.com","Emil#Foged43@yahoo.dk"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      1337,
      {x|["Emilie97@hotmail.com","Yasmin.Pedersen@outlook.dk"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      7,
      {x|["Karl{Emil.J6wrgensen-Johannsen@gmail.com","Emma_Iversen@hotmail.com"]|x}
    );
    ("internet.domainWord()", 42, {x|["ivrig-vindue","stille-park"]|x});
    ("internet.domainWord()", 1337, {x|["flsom-chance","glad-linje"]|x});
    ("internet.domainWord()", 7, {x|["billig-storm","krlig-skulptur"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 42, {x|["€375.15","€599.09"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 1337, {x|["€262.79","€459.85"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 7, {x|["€77.29","€723.75"]|x});
    ( "commerce.productName()",
      42,
      {x|["Håndlavet Træ Skjorte","Lækker Blød Bord"]|x} );
    ( "commerce.productName()",
      1337,
      {x|["Generisk Blød Fisk","Licenseret Bronze Mus"]|x} );
    ( "commerce.productName()",
      7,
      {x|["Elektronisk Plastik Kylling","Praktisk Træ Mus"]|x} );
    ("company.name()", 42, {x|["Vejle Visioner","Bruun Tasker ApS"]|x});
    ("company.name()", 1337, {x|["DaneBryg Bryggerier","Hedensted Handel"]|x});
    ("company.name()", 7, {x|["Ringsted Renovering","Nyborg Nytte"]|x});
    ( "finance.currencyName()",
      42,
      {x|["New Israeli Sheqel","CFA Franc BCEAO"]|x} );
    ("finance.currencyName()", 1337, {x|["Ethiopian Birr","Canadian Dollar"]|x});
    ("finance.currencyName()", 7, {x|["Barbados Dollar","Somali Shilling"]|x});
    ( "finance.creditCardNumber(\"visa\")",
      42,
      {x|["4975110867099","4211-3542-6123-4718"]|x} );
    ( "finance.creditCardNumber(\"visa\")",
      1337,
      {x|["4124352971364","4947734571266"]|x} );
    ( "finance.creditCardNumber(\"visa\")",
      7,
      {x|["4747955024684","4029249069258"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      42,
      {x|["2696-7511-0867-0988","2311-1354-2612-3471"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      1337,
      {x|["2300-2435-2971-3611","5377-3457-1264-1417"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      7,
      {x|["2610-4795-5024-6833","2365-9249-0692-5918"]|x} );
    ("animal.type()", 42, {x|["frog","whale"]|x});
    ("animal.type()", 1337, {x|["eagle","cow"]|x});
    ("animal.type()", 7, {x|["bird","rhinoceros"]|x});
    ( "system.fileName({\"extensionCount\":2})",
      42,
      {x|["straks_endelig.mar.xlw","imod_hallo.dot.m1v"]|x} );
    ( "system.fileName({\"extensionCount\":2})",
      1337,
      {x|["v_gt.jpg.distz","hos_leve.lrf.vsw"]|x} );
    ( "system.fileName({\"extensionCount\":2})",
      7,
      {x|["billig.xla.xhtml","ja_siden_magasin.xlsx.sh"]|x} );
    ( "food.dish()",
      42,
      {x|["Jicama Salad","Tangy Parsnip And White Flour Bowl"]|x} );
    ( "food.dish()",
      1337,
      {x|["Moist Green Beans And White Wine Vinegar Bowl","Bruschette With Tomato"]|x}
    );
    ("food.dish()", 7, {x|["Parsley-rubbed Ostrich Salad","Baba Ganoush"]|x});
    ( "music.songName()",
      42,
      {x|["I Honestly Love You","Why Do Fools Fall in Love?"]|x} );
    ("music.songName()", 1337, {x|["Frankenstein","Cars"]|x});
    ("music.songName()", 7, {x|["Bad Day","Take Me Home, Country Roads"]|x});
    ("book.title()", 42, {x|["Lord Jim","Tropic of Cancer"]|x});
    ("book.title()", 1337, {x|["Gone with the Wind","Candide"]|x});
    ( "book.title()",
      7,
      {x|["All Quiet on the Western Front","The Pickwick Papers"]|x} );
    ("vehicle.vehicle()", 42, {x|["Jeep Wrangler","Renault Impala"]|x});
    ("vehicle.vehicle()", 1337, {x|["Fiat Aventador","Ford Explorer"]|x});
    ("vehicle.vehicle()", 7, {x|["BYD Mustang","Land Rover Model X"]|x});
  ]
