(* GENERATED by tools/gen_fixtures.mjs from tools/cases/l10n.mjs - do not edit. *)

let locale = "pt_PT"

let cases =
  [
    ("person.firstName(\"female\")", 42, {x|["Francisca","Vitória"]|x});
    ("person.firstName(\"female\")", 1337, {x|["Diana","Carlota"]|x});
    ("person.firstName(\"female\")", 7, {x|["Beatriz","Olívia"]|x});
    ("person.firstName(\"male\")", 42, {x|["Igor","Vicente"]|x});
    ("person.firstName(\"male\")", 1337, {x|["Frederico","Duarte"]|x});
    ("person.firstName(\"male\")", 7, {x|["Bruno","Romeu"]|x});
    ("person.lastName(\"female\")", 42, {x|["Valente","Mesquita"]|x});
    ("person.lastName(\"female\")", 1337, {x|["Branco","Lopes"]|x});
    ("person.lastName(\"female\")", 7, {x|["Pinho","Oliveira"]|x});
    ("person.lastName(\"male\")", 42, {x|["Valente","Mesquita"]|x});
    ("person.lastName(\"male\")", 1337, {x|["Branco","Lopes"]|x});
    ("person.lastName(\"male\")", 7, {x|["Pinho","Oliveira"]|x});
    ("person.middleName(\"female\")", 42, {x|["Venus","Kali"]|x});
    ("person.middleName(\"female\")", 1337, {x|["Brielle","Hippolyta"]|x});
    ("person.middleName(\"female\")", 7, {x|["Michelle","Maddie"]|x});
    ( "person.fullName({\"sex\":\"female\"})",
      42,
      {x|["Francisca Pacheco","Carlota Andrade"]|x} );
    ( "person.fullName({\"sex\":\"female\"})",
      1337,
      {x|["Diana Esteves","Prof.ª Emília Cunha"]|x} );
    ( "person.fullName({\"sex\":\"female\"})",
      7,
      {x|["Beatriz Leite","Áurea Machado"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      42,
      {x|["Igor Pacheco","Diogo Andrade"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      1337,
      {x|["Frederico Esteves","Prof. Guilherme Cunha"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      7,
      {x|["Bruno Leite","Xavier Machado"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      42,
      {x|["Anna Pacheco","Anna Andrade"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      1337,
      {x|["Anna Esteves","Prof.ª Anna Cunha"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      7,
      {x|["Anna Leite","Anna Machado"]|x} );
    ("person.prefix(\"female\")", 42, {x|["Dra.","Téc.ª"]|x});
    ("person.prefix(\"female\")", 1337, {x|["Dra.","Arq.ª"]|x});
    ("person.prefix(\"female\")", 7, {x|["Adv.ª","Sra."]|x});
    ("person.prefix(\"male\")", 42, {x|["Dr.","Téc."]|x});
    ("person.prefix(\"male\")", 1337, {x|["Dr.","Arq."]|x});
    ("person.prefix(\"male\")", 7, {x|["Adv.","Sr."]|x});
    ( "person.suffix()",
      42,
      {x|[{"error":"The locale data for 'person.suffix' aren't applicable to this locale.\n  If you think this is a bug, please report it at: https://github.com/faker-js/faker"},{"error":"The locale data for 'person.suffix' aren't applicable to this locale.\n  If you think this is a bug, please report it at: https://github.com/faker-js/faker"}]|x}
    );
    ( "person.suffix()",
      1337,
      {x|[{"error":"The locale data for 'person.suffix' aren't applicable to this locale.\n  If you think this is a bug, please report it at: https://github.com/faker-js/faker"},{"error":"The locale data for 'person.suffix' aren't applicable to this locale.\n  If you think this is a bug, please report it at: https://github.com/faker-js/faker"}]|x}
    );
    ( "person.suffix()",
      7,
      {x|[{"error":"The locale data for 'person.suffix' aren't applicable to this locale.\n  If you think this is a bug, please report it at: https://github.com/faker-js/faker"},{"error":"The locale data for 'person.suffix' aren't applicable to this locale.\n  If you think this is a bug, please report it at: https://github.com/faker-js/faker"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      42,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      1337,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      7,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      42,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      1337,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      7,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ("location.zipCode(\"###\")", 42, {x|["397","511"]|x});
    ("location.zipCode(\"###\")", 1337, {x|["212","435"]|x});
    ("location.zipCode(\"###\")", 7, {x|["074","795"]|x});
    ("location.state({\"abbreviated\":true})", 42, {x|["ME","WV"]|x});
    ("location.state({\"abbreviated\":true})", 1337, {x|["IN","DE"]|x});
    ("location.state({\"abbreviated\":true})", 7, {x|["AR","RI"]|x});
    ( "location.streetAddress(true)",
      42,
      {x|["Caminho Raul Braga 8670-Escr.","Rua Carmo Mariz 361-4A"]|x} );
    ( "location.streetAddress(true)",
      1337,
      {x|["Beco Débora Maia 971-6C","Avenida Josué Furtado 671-7A"]|x} );
    ( "location.streetAddress(true)",
      7,
      {x|["Alameda Jorge Martins 12-Ed.","Praça Isac Sousa 5906-Escr."]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      42,
      {x|["Caminho Raul Braga 8670-Escr.","Rua Carmo Mariz 361-4A"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      1337,
      {x|["Beco Débora Maia 971-6C","Avenida Josué Furtado 671-7A"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      7,
      {x|["Alameda Jorge Martins 12-Ed.","Praça Isac Sousa 5906-Escr."]|x} );
    ("location.countryCode(\"alpha-3\")", 42, {x|["GUY","VCT"]|x});
    ("location.countryCode(\"alpha-3\")", 1337, {x|["ESH","COD"]|x});
    ("location.countryCode(\"alpha-3\")", 7, {x|["BEL","SYC"]|x});
    ("location.countryCode(\"numeric\")", 42, {x|["328","670"]|x});
    ("location.countryCode(\"numeric\")", 1337, {x|["732","180"]|x});
    ("location.countryCode(\"numeric\")", 7, {x|["056","690"]|x});
    ( "location.timeZone()",
      42,
      {x|["America/North_Dakota/Center","Pacific/Kosrae"]|x} );
    ( "location.timeZone()",
      1337,
      {x|["America/Guadeloupe","America/Argentina/San_Luis"]|x} );
    ("location.timeZone()", 7, {x|["Africa/Libreville","Europe/Gibraltar"]|x});
    ("date.month({\"abbreviated\":true})", 42, {x|["Jan","Set"]|x});
    ("date.month({\"abbreviated\":true})", 1337, {x|["Fev","Ago"]|x});
    ("date.month({\"abbreviated\":true})", 7, {x|["Abr","Nov"]|x});
    ("date.month({\"context\":true})", 42, {x|["Janeiro","Setembro"]|x});
    ("date.month({\"context\":true})", 1337, {x|["Fevereiro","Agosto"]|x});
    ("date.month({\"context\":true})", 7, {x|["Abril","Novembro"]|x});
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      42,
      {x|["Jan","Set"]|x} );
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      1337,
      {x|["Fev","Ago"]|x} );
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      7,
      {x|["Abr","Nov"]|x} );
    ("date.weekday({\"abbreviated\":true})", 42, {x|["Qui","Ter"]|x});
    ("date.weekday({\"abbreviated\":true})", 1337, {x|["Qua","Qua"]|x});
    ("date.weekday({\"abbreviated\":true})", 7, {x|["Dom","Sáb"]|x});
    ("date.weekday({\"context\":true})", 42, {x|["Quinta","Terça"]|x});
    ("date.weekday({\"context\":true})", 1337, {x|["Quarta","Quarta"]|x});
    ("date.weekday({\"context\":true})", 7, {x|["Domingo","Sábado"]|x});
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      42,
      {x|["Qui","Ter"]|x} );
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      1337,
      {x|["Qua","Qua"]|x} );
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      7,
      {x|["Dom","Sáb"]|x} );
    ( "phone.number({\"style\":\"human\"})",
      42,
      {x|["+351 919751108","+351 937098211"]|x} );
    ( "phone.number({\"style\":\"human\"})",
      1337,
      {x|["+351 911243529","+351 931361947"]|x} );
    ( "phone.number({\"style\":\"human\"})",
      7,
      {x|["+351 274795502","+351 926830292"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      42,
      {x|["919 751 108","937 098 211"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      1337,
      {x|["911 243 529","931 361 947"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      7,
      {x|["274 795 502","926 830 292"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      42,
      {x|["+351919751108","+351937098211"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      1337,
      {x|["+351911243529","+351931361947"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      7,
      {x|["+351274795502","+351926830292"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      42,
      {x|["feliz","tímido"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      1337,
      {x|["divino","bom"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      7,
      {x|["ativo","pobre"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      42,
      {x|["gasto","vídeo"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      1337,
      {x|["cobra","calça"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      7,
      {x|["avião","preço"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      42,
      {x|["rir","ver"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      1337,
      {x|["ler","ler"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      7,
      {x|["ler","ver"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      42,
      {x|["even","doce"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      1337,
      {x|["once","when"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      7,
      {x|["sair","anti"]|x} );
    ( "word.words(5)",
      42,
      {x|["bleakly cobertor gee psst why","meh ugh sujo wherever without"]|x} );
    ( "word.words(5)",
      1337,
      {x|["how yet pesado cidade including","safely joelho actually aceitar vaguely"]|x}
    );
    ( "word.words(5)",
      7,
      {x|["florescer afore eek preço circa","digitalizar colorido yuck andar grande"]|x}
    );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      42,
      {x|["crux","vito"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      1337,
      {x|["ceno","arma"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      7,
      {x|["alii","tibi"]|x} );
    ( "lorem.sentences(3)",
      42,
      {x|["Virga synagoga patruus armarium armarium. Usitas paulatim suggero. Volubilis tristis benevolentia.","Auctus cognomen esse custodia. Perspiciatis apud claro copiose defleo. Aveho doloribus omnis adipiscor pectus assumenda advoco vinum vociferor."]|x}
    );
    ( "lorem.sentences(3)",
      1337,
      {x|["Articulus chirographum degenero commemoro eaque. Voluptatibus tabella ancilla creptio quisquam. Vorago decipio testimonium thalassinus.","Cupressus nulla temporibus audeo civis. Desidero atrox cupiditate avarus exercitationem tristis audax vita. Desparatus dolore accendo suus vulgo ascisco."]|x}
    );
    ( "lorem.sentences(3)",
      7,
      {x|["Termes debitis supra. Fugiat desino aequitas censura desidero spoliatio thymbra creator aedificium civis. Benigne defero vicinus acidus pauci virga callide infit verbera appello.","Tandem sortitus delibero bardus deprecator corroboro demoror. Tum tenuis combibo nam cetera. Conservo solum corpus degenero super cupiditate."]|x}
    );
    ( "lorem.paragraphs(2)",
      42,
      {x|["Virga synagoga patruus armarium armarium. Usitas paulatim suggero. Volubilis tristis benevolentia.\nAuctus cognomen esse custodia. Perspiciatis apud claro copiose defleo. Aveho doloribus omnis adipiscor pectus assumenda advoco vinum vociferor.","Cogo alter stella decerno animus deputo adeo verbera caute. Color eius incidunt audacia volubilis terga vigor varius. Verus alienus autus adipisci comparo creta cernuus.\nConsuasor cicuta illo aqua thorax aestas vos ter avarus. Tot suffragium suspendo. Aer contego ancilla urbanus qui comptus adversus colo communis."]|x}
    );
    ( "lorem.paragraphs(2)",
      1337,
      {x|["Articulus chirographum degenero commemoro eaque. Voluptatibus tabella ancilla creptio quisquam. Vorago decipio testimonium thalassinus.\nCupressus nulla temporibus audeo civis. Desidero atrox cupiditate avarus exercitationem tristis audax vita. Desparatus dolore accendo suus vulgo ascisco.","Corrupti suadeo abbas corporis. Testimonium consectetur subvenio. Voluptas tubineus pel magni vulpes caterva.\nAlienus vigor voluptate. Confugo supra abstergo temporibus speciosus aufero. Vere arx verbum communis subseco cena earum atrocitas."]|x}
    );
    ( "lorem.paragraphs(2)",
      7,
      {x|["Termes debitis supra. Fugiat desino aequitas censura desidero spoliatio thymbra creator aedificium civis. Benigne defero vicinus acidus pauci virga callide infit verbera appello.\nTandem sortitus delibero bardus deprecator corroboro demoror. Tum tenuis combibo nam cetera. Conservo solum corpus degenero super cupiditate.","Attollo talio curis curso reiciendis eos cuppedia ab aliquam sui. Subito vis statua adnuo colligo optio canonicus. Vinculum ubi demens turba aperte colligo delectatio talis depereo approbo.\nCommunis coerceo asperiores cuppedia dedico. Theca enim degusto tergo valens spero thesaurus vigor adhaero. Charisma demonstro theca sunt arceo soluta aegrus consuasor torqueo cursus."]|x}
    );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      42,
      {x|["Jurgen_60degard@live.com","Jurgen.60degard@gmail.com"]|x} );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      1337,
      {x|["Jurgen.60degard27@hotmail.com","Jurgen_60degard@hotmail.com"]|x} );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      7,
      {x|["Jurgen_60degard@aeiou.pt","Jurgen_60degard50@yahoo.com"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      42,
      {x|["Anna.8xukasz","Anna_8xukasz15"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      1337,
      {x|["Anna.8xukasz15","Anna.8xukasz"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      7,
      {x|["Anna.8xukasz77","Anna_8xukasz"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      42,
      {x|["Zoë15","Zoë_Mesquita2"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      1337,
      {x|["Zoë.Esteves","Zoë.Pacheco"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      7,
      {x|["Zoë_Leite","Zoë.Domingues67"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      42,
      {x|["Raul.Braga@live.com","Feliciano#Fernandes43@yahoo.com"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      1337,
      {x|["Debora97@hotmail.com","Erica.Pires@outlook.com"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      7,
      {x|["Jorge^Martins7@aeiou.pt","Aurora.Carvalho93@sapo.pt"]|x} );
    ("internet.domainWord()", 42, {x|["feio-urna","paciente-moto"]|x});
    ("internet.domainWord()", 1337, {x|["dificil-cantor","doce-hotel"]|x});
    ("internet.domainWord()", 7, {x|["barato-rato","facil-poder"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 42, {x|["€375.15","€599.09"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 1337, {x|["€262.79","€459.85"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 7, {x|["€77.29","€723.75"]|x});
    ( "commerce.productName()",
      42,
      {x|["Carro Sem Marca de Metal","Peixe Fantástico de Aço"]|x} );
    ( "commerce.productName()",
      1337,
      {x|["Calças Fantástico de Borracha","Frango Impressionante de Fresco"]|x}
    );
    ( "commerce.productName()",
      7,
      {x|["Bacon Refinado de Congelado","Rato Sem Marca de Fresco"]|x} );
    ("company.name()", 42, {x|["Mesquita e Andrade","Almeida ULTDA"]|x});
    ("company.name()", 1337, {x|["Lopes e Cunha","Gomes SCR"]|x});
    ("company.name()", 7, {x|["Oliveira e Machado","Neves e Andrade"]|x});
    ( "finance.currencyName()",
      42,
      {x|["New Israeli Sheqel","CFA Franc BCEAO"]|x} );
    ("finance.currencyName()", 1337, {x|["Ethiopian Birr","Canadian Dollar"]|x});
    ("finance.currencyName()", 7, {x|["Barbados Dollar","Somali Shilling"]|x});
    ( "finance.creditCardNumber(\"visa\")",
      42,
      {x|["4975110867099","4211-3542-6123-4718"]|x} );
    ( "finance.creditCardNumber(\"visa\")",
      1337,
      {x|["4124352971364","4947734571266"]|x} );
    ( "finance.creditCardNumber(\"visa\")",
      7,
      {x|["4747955024684","4029249069258"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      42,
      {x|["2696-7511-0867-0988","2311-1354-2612-3471"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      1337,
      {x|["2300-2435-2971-3611","5377-3457-1264-1417"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      7,
      {x|["2610-4795-5024-6833","2365-9249-0692-5918"]|x} );
    ("animal.type()", 42, {x|["frog","whale"]|x});
    ("animal.type()", 1337, {x|["eagle","cow"]|x});
    ("animal.type()", 7, {x|["bird","rhinoceros"]|x});
    ( "system.fileName({\"extensionCount\":2})",
      42,
      {x|["unnaturally_dreamily.mar.xlw","following_huzzah.dot.m1v"]|x} );
    ( "system.fileName({\"extensionCount\":2})",
      1337,
      {x|["voto.jpg.distz","circa_florescer.lrf.vsw"]|x} );
    ( "system.fileName({\"extensionCount\":2})",
      7,
      {x|["baixo.xla.xhtml","drat_who_joelho.xlsx.sh"]|x} );
    ( "food.dish()",
      42,
      {x|["Jicama Salad","Tangy Parsnip And White Flour Bowl"]|x} );
    ( "food.dish()",
      1337,
      {x|["Moist Green Beans And White Wine Vinegar Bowl","Bruschette With Tomato"]|x}
    );
    ("food.dish()", 7, {x|["Parsley-rubbed Ostrich Salad","Baba Ganoush"]|x});
    ( "music.songName()",
      42,
      {x|["I Honestly Love You","Why Do Fools Fall in Love?"]|x} );
    ("music.songName()", 1337, {x|["Frankenstein","Cars"]|x});
    ("music.songName()", 7, {x|["Bad Day","Take Me Home, Country Roads"]|x});
    ("book.title()", 42, {x|["Lord Jim","Tropic of Cancer"]|x});
    ("book.title()", 1337, {x|["Gone with the Wind","Candide"]|x});
    ( "book.title()",
      7,
      {x|["All Quiet on the Western Front","The Pickwick Papers"]|x} );
    ("vehicle.vehicle()", 42, {x|["Jeep Wrangler","Renault Impala"]|x});
    ("vehicle.vehicle()", 1337, {x|["Fiat Aventador","Ford Explorer"]|x});
    ("vehicle.vehicle()", 7, {x|["BYD Mustang","Land Rover Model X"]|x});
  ]
