(* GENERATED by tools/gen_fixtures.mjs from tools/cases/l10n.mjs - do not edit. *)

let locale = "nb_NO"

let cases =
  [
    ("person.firstName(\"female\")", 42, {x|["Kaja","Tuva"]|x});
    ("person.firstName(\"female\")", 1337, {x|["Helene","Elise"]|x});
    ("person.firstName(\"female\")", 7, {x|["Aurora","Sandra"]|x});
    ("person.firstName(\"male\")", 42, {x|["Jakob","Thomas"]|x});
    ("person.firstName(\"male\")", 1337, {x|["Fredrik","Eirik"]|x});
    ("person.firstName(\"male\")", 7, {x|["Anders","Ole"]|x});
    ("person.lastName(\"female\")", 42, {x|["Vegge","Mathisen"]|x});
    ("person.lastName(\"female\")", 1337, {x|["Borge","Johnsen"]|x});
    ("person.lastName(\"female\")", 7, {x|["Skoglund","Pettersen"]|x});
    ("person.lastName(\"male\")", 42, {x|["Vegge","Mathisen"]|x});
    ("person.lastName(\"male\")", 1337, {x|["Borge","Johnsen"]|x});
    ("person.lastName(\"male\")", 7, {x|["Skoglund","Pettersen"]|x});
    ("person.middleName(\"female\")", 42, {x|["Venus","Kali"]|x});
    ("person.middleName(\"female\")", 1337, {x|["Brielle","Hippolyta"]|x});
    ("person.middleName(\"female\")", 7, {x|["Michelle","Maddie"]|x});
    ( "person.fullName({\"sex\":\"female\"})",
      42,
      {x|["Kaja Rasmussen Mathisen Sr.","Prof. Anna Moe Olstad"]|x} );
    ( "person.fullName({\"sex\":\"female\"})",
      1337,
      {x|["Helene Fredriksen","Jenny Fossum"]|x} );
    ( "person.fullName({\"sex\":\"female\"})",
      7,
      {x|["Aurora Johannessen","Dr. Victoria Kristiansen"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      42,
      {x|["Jakob Rasmussen Mathisen Sr.","Prof. Alexander Moe Olstad"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      1337,
      {x|["Fredrik Fredriksen","Håkon Fossum"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      7,
      {x|["Anders Johannessen","Dr. Tobias Kristiansen"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      42,
      {x|["Anna Rasmussen Mathisen Sr.","Prof. Anna Moe Olstad"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      1337,
      {x|["Anna Fredriksen","Anna Fossum"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      7,
      {x|["Anna Johannessen","Dr. Anna Kristiansen"]|x} );
    ("person.prefix(\"female\")", 42, {x|["Dr.","Prof."]|x});
    ("person.prefix(\"female\")", 1337, {x|["Dr.","Dr."]|x});
    ("person.prefix(\"female\")", 7, {x|["Dr.","Prof."]|x});
    ("person.prefix(\"male\")", 42, {x|["Dr.","Prof."]|x});
    ("person.prefix(\"male\")", 1337, {x|["Dr.","Dr."]|x});
    ("person.prefix(\"male\")", 7, {x|["Dr.","Prof."]|x});
    ("person.suffix()", 42, {x|["I","V"]|x});
    ("person.suffix()", 1337, {x|["Sr.","Sr."]|x});
    ("person.suffix()", 7, {x|["Jr.","IV"]|x});
    ( "location.zipCode({\"state\":\"CA\"})",
      42,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      1337,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      7,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      42,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      1337,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      7,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ("location.zipCode(\"###\")", 42, {x|["397","511"]|x});
    ("location.zipCode(\"###\")", 1337, {x|["212","435"]|x});
    ("location.zipCode(\"###\")", 7, {x|["074","795"]|x});
    ("location.state({\"abbreviated\":true})", 42, {x|["ME","WV"]|x});
    ("location.state({\"abbreviated\":true})", 1337, {x|["IN","DE"]|x});
    ("location.state({\"abbreviated\":true})", 7, {x|["AR","RI"]|x});
    ( "location.streetAddress(true)",
      42,
      {x|["Vestre Geiteryggmyra 2 Leil. 867","Sjøstykket 2 Leil. 354"]|x} );
    ( "location.streetAddress(true)",
      1337,
      {x|["Øvre Elvelia 5 Leil. 971","Gamle Furuåsen 8 Oppgang B"]|x} );
    ( "location.streetAddress(true)",
      7,
      {x|["Bekkekroken 95 Oppgang A","Fosselunden 83 Leil. 392"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      42,
      {x|["Vestre Geiteryggmyra 2 Leil. 867","Sjøstykket 2 Leil. 354"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      1337,
      {x|["Øvre Elvelia 5 Leil. 971","Gamle Furuåsen 8 Oppgang B"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      7,
      {x|["Bekkekroken 95 Oppgang A","Fosselunden 83 Leil. 392"]|x} );
    ("location.countryCode(\"alpha-3\")", 42, {x|["GUY","VCT"]|x});
    ("location.countryCode(\"alpha-3\")", 1337, {x|["ESH","COD"]|x});
    ("location.countryCode(\"alpha-3\")", 7, {x|["BEL","SYC"]|x});
    ("location.countryCode(\"numeric\")", 42, {x|["328","670"]|x});
    ("location.countryCode(\"numeric\")", 1337, {x|["732","180"]|x});
    ("location.countryCode(\"numeric\")", 7, {x|["056","690"]|x});
    ( "location.timeZone()",
      42,
      {x|["America/North_Dakota/Center","Pacific/Kosrae"]|x} );
    ( "location.timeZone()",
      1337,
      {x|["America/Guadeloupe","America/Argentina/San_Luis"]|x} );
    ("location.timeZone()", 7, {x|["Africa/Libreville","Europe/Gibraltar"]|x});
    ("date.month({\"abbreviated\":true})", 42, {x|["Jan","Sep"]|x});
    ("date.month({\"abbreviated\":true})", 1337, {x|["Feb","Aug"]|x});
    ("date.month({\"abbreviated\":true})", 7, {x|["Apr","Nov"]|x});
    ("date.month({\"context\":true})", 42, {x|["January","September"]|x});
    ("date.month({\"context\":true})", 1337, {x|["February","August"]|x});
    ("date.month({\"context\":true})", 7, {x|["April","November"]|x});
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      42,
      {x|["Jan","Sep"]|x} );
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      1337,
      {x|["Feb","Aug"]|x} );
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      7,
      {x|["Apr","Nov"]|x} );
    ("date.weekday({\"abbreviated\":true})", 42, {x|["Sat","Wed"]|x});
    ("date.weekday({\"abbreviated\":true})", 1337, {x|["Mon","Mon"]|x});
    ("date.weekday({\"abbreviated\":true})", 7, {x|["Fri","Tue"]|x});
    ("date.weekday({\"context\":true})", 42, {x|["Saturday","Wednesday"]|x});
    ("date.weekday({\"context\":true})", 1337, {x|["Monday","Monday"]|x});
    ("date.weekday({\"context\":true})", 7, {x|["Friday","Tuesday"]|x});
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      42,
      {x|["Sat","Wed"]|x} );
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      1337,
      {x|["Mon","Mon"]|x} );
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      7,
      {x|["Fri","Tue"]|x} );
    ("phone.number({\"style\":\"human\"})", 42, {x|["975 11 086","09821135"]|x});
    ( "phone.number({\"style\":\"human\"})",
      1337,
      {x|["124 35 297","36 19 47 73"]|x} );
    ( "phone.number({\"style\":\"human\"})",
      7,
      {x|["74 79 55 02","683 02 924"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      42,
      {x|["39 75 11 08","67 09 82 11"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      1337,
      {x|["21 24 35 29","71 36 19 47"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      7,
      {x|["07 47 95 50","24 68 30 29"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      42,
      {x|["+4739751108","+4767098211"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      1337,
      {x|["+4721243529","+4771361947"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      7,
      {x|["+4707479550","+4724683029"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      42,
      {x|["lat","voksen"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      1337,
      {x|["følsom","falsk"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      7,
      {x|["ekkel","stygg"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      42,
      {x|["guide","whack"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      1337,
      {x|["equal","daddy"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      7,
      {x|["brief","stall"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      42,
      {x|["jot","veg"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      1337,
      {x|["gad","cow"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      7,
      {x|["bus","sit"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      42,
      {x|["even","deer"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      1337,
      {x|["for","så"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      7,
      {x|["lend","anti"]|x} );
    ( "word.words(5)",
      42,
      {x|["bleakly custody nam hæ så","hæ jippi vellykket så without"]|x} );
    ( "word.words(5)",
      1337,
      {x|["for så stolt councilman including","safely junior actually accredit vaguely"]|x}
    );
    ( "word.words(5)",
      7,
      {x|["masticate afore nam requirement circa","forswear fjern aha bank motsatt"]|x}
    );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      42,
      {x|["crux","vito"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      1337,
      {x|["ceno","arma"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      7,
      {x|["alii","tibi"]|x} );
    ( "lorem.sentences(3)",
      42,
      {x|["Virga synagoga patruus armarium armarium. Usitas paulatim suggero. Volubilis tristis benevolentia.","Auctus cognomen esse custodia. Perspiciatis apud claro copiose defleo. Aveho doloribus omnis adipiscor pectus assumenda advoco vinum vociferor."]|x}
    );
    ( "lorem.sentences(3)",
      1337,
      {x|["Articulus chirographum degenero commemoro eaque. Voluptatibus tabella ancilla creptio quisquam. Vorago decipio testimonium thalassinus.","Cupressus nulla temporibus audeo civis. Desidero atrox cupiditate avarus exercitationem tristis audax vita. Desparatus dolore accendo suus vulgo ascisco."]|x}
    );
    ( "lorem.sentences(3)",
      7,
      {x|["Termes debitis supra. Fugiat desino aequitas censura desidero spoliatio thymbra creator aedificium civis. Benigne defero vicinus acidus pauci virga callide infit verbera appello.","Tandem sortitus delibero bardus deprecator corroboro demoror. Tum tenuis combibo nam cetera. Conservo solum corpus degenero super cupiditate."]|x}
    );
    ( "lorem.paragraphs(2)",
      42,
      {x|["Virga synagoga patruus armarium armarium. Usitas paulatim suggero. Volubilis tristis benevolentia.\nAuctus cognomen esse custodia. Perspiciatis apud claro copiose defleo. Aveho doloribus omnis adipiscor pectus assumenda advoco vinum vociferor.","Cogo alter stella decerno animus deputo adeo verbera caute. Color eius incidunt audacia volubilis terga vigor varius. Verus alienus autus adipisci comparo creta cernuus.\nConsuasor cicuta illo aqua thorax aestas vos ter avarus. Tot suffragium suspendo. Aer contego ancilla urbanus qui comptus adversus colo communis."]|x}
    );
    ( "lorem.paragraphs(2)",
      1337,
      {x|["Articulus chirographum degenero commemoro eaque. Voluptatibus tabella ancilla creptio quisquam. Vorago decipio testimonium thalassinus.\nCupressus nulla temporibus audeo civis. Desidero atrox cupiditate avarus exercitationem tristis audax vita. Desparatus dolore accendo suus vulgo ascisco.","Corrupti suadeo abbas corporis. Testimonium consectetur subvenio. Voluptas tubineus pel magni vulpes caterva.\nAlienus vigor voluptate. Confugo supra abstergo temporibus speciosus aufero. Vere arx verbum communis subseco cena earum atrocitas."]|x}
    );
    ( "lorem.paragraphs(2)",
      7,
      {x|["Termes debitis supra. Fugiat desino aequitas censura desidero spoliatio thymbra creator aedificium civis. Benigne defero vicinus acidus pauci virga callide infit verbera appello.\nTandem sortitus delibero bardus deprecator corroboro demoror. Tum tenuis combibo nam cetera. Conservo solum corpus degenero super cupiditate.","Attollo talio curis curso reiciendis eos cuppedia ab aliquam sui. Subito vis statua adnuo colligo optio canonicus. Vinculum ubi demens turba aperte colligo delectatio talis depereo approbo.\nCommunis coerceo asperiores cuppedia dedico. Theca enim degusto tergo valens spero thesaurus vigor adhaero. Charisma demonstro theca sunt arceo soluta aegrus consuasor torqueo cursus."]|x}
    );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      42,
      {x|["Jurgen_60degard@hotmail.com","Jurgen.60degard@gmail.com"]|x} );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      1337,
      {x|["Jurgen.60degard27@gmail.com","Jurgen_60degard@gmail.com"]|x} );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      7,
      {x|["Jurgen_60degard@gmail.com","Jurgen_60degard50@yahoo.com"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      42,
      {x|["Anna.8xukasz","Anna_8xukasz15"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      1337,
      {x|["Anna.8xukasz15","Anna.8xukasz"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      7,
      {x|["Anna.8xukasz77","Anna_8xukasz"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      42,
      {x|["Zoë15","Zoë.Olstad96"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      1337,
      {x|["Zoë.Fredriksen","Zoë62"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      7,
      {x|["Zoë_Johannessen","Zoë.Fossum67"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      42,
      {x|["Nikolai.Borge@hotmail.com","Erik#Gundersen43@yahoo.com"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      1337,
      {x|["Helene97@gmail.com","Vilde.Smedsrud@hotmail.com"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      7,
      {x|["Jonas.KvarmeKristiansen@gmail.com","Ida_Johnsen@hotmail.com"]|x} );
    ("internet.domainWord()", 42, {x|["lovlig-unit","st-negotiation"]|x});
    ( "internet.domainWord()",
      1337,
      {x|["heldig-co-producer","hjelpsom-in-joke"]|x} );
    ("internet.domainWord()", 7, {x|["dyp-saw","modig-puritan"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 42, {x|["€375.15","€599.09"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 1337, {x|["€262.79","€459.85"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 7, {x|["€77.29","€723.75"]|x});
    ( "commerce.productName()",
      42,
      {x|["Handcrafted Wooden Sausages","Modern Bronze Car"]|x} );
    ( "commerce.productName()",
      1337,
      {x|["Frozen Bronze Chicken","Incredible Concrete Keyboard"]|x} );
    ( "commerce.productName()",
      7,
      {x|["Electronic Rubber Gloves","Recycled Wooden Keyboard"]|x} );
    ( "company.name()",
      42,
      {x|["Mathisen, Andreassen og Olstad","Eide Dahl ASA"]|x} );
    ( "company.name()",
      1337,
      {x|["Johnsen ASA","Rasmussen Berge, Berntsen og Skuterud"]|x} );
    ( "company.name()",
      7,
      {x|["Pettersen og Sønner","Fossum, Smogeli og Glosli"]|x} );
    ( "finance.currencyName()",
      42,
      {x|["New Israeli Sheqel","CFA Franc BCEAO"]|x} );
    ("finance.currencyName()", 1337, {x|["Ethiopian Birr","Canadian Dollar"]|x});
    ("finance.currencyName()", 7, {x|["Barbados Dollar","Somali Shilling"]|x});
    ( "finance.creditCardNumber(\"visa\")",
      42,
      {x|["4975110867099","4211-3542-6123-4718"]|x} );
    ( "finance.creditCardNumber(\"visa\")",
      1337,
      {x|["4124352971364","4947734571266"]|x} );
    ( "finance.creditCardNumber(\"visa\")",
      7,
      {x|["4747955024684","4029249069258"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      42,
      {x|["2696-7511-0867-0988","2311-1354-2612-3471"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      1337,
      {x|["2300-2435-2971-3611","5377-3457-1264-1417"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      7,
      {x|["2610-4795-5024-6833","2365-9249-0692-5918"]|x} );
    ("animal.type()", 42, {x|["hai","ugle"]|x});
    ("animal.type()", 1337, {x|["gaupe","elefant"]|x});
    ("animal.type()", 7, {x|["bie","rotte"]|x});
    ( "system.fileName({\"extensionCount\":2})",
      42,
      {x|["unnaturally_dreamily.mar.xlw","following_bravo.dot.m1v"]|x} );
    ( "system.fileName({\"extensionCount\":2})",
      1337,
      {x|["wallaby.jpg.distz","circa_masquerade.lrf.vsw"]|x} );
    ( "system.fileName({\"extensionCount\":2})",
      7,
      {x|["dum.xla.xhtml","hurra_s__jungle.xlsx.sh"]|x} );
    ("food.dish()", 42, {x|["Magnus Sin Spesielle Bønner","Rosenkålsalat"]|x});
    ( "food.dish()",
      1337,
      {x|["Panert Pastinakksalat","Benjamin Sin Spesielle Mel"]|x} );
    ("food.dish()", 7, {x|["Rødbete Og Linsergryte","Brunost"]|x});
    ( "music.songName()",
      42,
      {x|["I Honestly Love You","Why Do Fools Fall in Love?"]|x} );
    ("music.songName()", 1337, {x|["Frankenstein","Cars"]|x});
    ("music.songName()", 7, {x|["Bad Day","Take Me Home, Country Roads"]|x});
    ("book.title()", 42, {x|["Lord Jim","Tropic of Cancer"]|x});
    ("book.title()", 1337, {x|["Gone with the Wind","Candide"]|x});
    ( "book.title()",
      7,
      {x|["All Quiet on the Western Front","The Pickwick Papers"]|x} );
    ("vehicle.vehicle()", 42, {x|["Jeep Wrangler","Renault Impala"]|x});
    ("vehicle.vehicle()", 1337, {x|["Fiat Aventador","Ford Explorer"]|x});
    ("vehicle.vehicle()", 7, {x|["BYD Mustang","Land Rover Model X"]|x});
  ]
