(* GENERATED by tools/gen_fixtures.mjs from tools/cases/l10n.mjs - do not edit. *)

let locale = "fa"

let cases =
  [
    ("person.firstName(\"female\")", 42, {x|["گلاره","مهر آرا"]|x});
    ("person.firstName(\"female\")", 1337, {x|["ترانه","فرانک"]|x});
    ("person.firstName(\"female\")", 7, {x|["هانیه","نازنین"]|x});
    ("person.firstName(\"male\")", 42, {x|["کسرا","مهر آرا"]|x});
    ("person.firstName(\"male\")", 1337, {x|["ایمان","شهروز"]|x});
    ("person.firstName(\"male\")", 7, {x|["مهرداد","مهدی"]|x});
    ("person.lastName(\"female\")", 42, {x|["کیمیایی","میردامادی"]|x});
    ("person.lastName(\"female\")", 1337, {x|["فانی","مصباح"]|x});
    ("person.lastName(\"female\")", 7, {x|["همت","هاشمی"]|x});
    ("person.lastName(\"male\")", 42, {x|["کیمیایی","میردامادی"]|x});
    ("person.lastName(\"male\")", 1337, {x|["فانی","مصباح"]|x});
    ("person.lastName(\"male\")", 7, {x|["همت","هاشمی"]|x});
    ("person.middleName(\"female\")", 42, {x|["Venus","Kali"]|x});
    ("person.middleName(\"female\")", 1337, {x|["Brielle","Hippolyta"]|x});
    ("person.middleName(\"female\")", 7, {x|["Michelle","Maddie"]|x});
    ( "person.fullName({\"sex\":\"female\"})",
      42,
      {x|["گلاره میردامادی","آناهیتا میردامادی"]|x} );
    ( "person.fullName({\"sex\":\"female\"})",
      1337,
      {x|["ترانه مصباح","رودابه هاشمی رفسنجانی"]|x} );
    ( "person.fullName({\"sex\":\"female\"})",
      7,
      {x|["هانیه هاشمی","فروزان قمیشی"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      42,
      {x|["کسرا میردامادی","آیدین میردامادی"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      1337,
      {x|["ایمان مصباح","رودابه هاشمی رفسنجانی"]|x} );
    ( "person.fullName({\"sex\":\"male\"})",
      7,
      {x|["مهرداد هاشمی","فروزان قمیشی"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      42,
      {x|["Anna هاشمی رفسنجانی","Anna عصار"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      1337,
      {x|["Anna قهرمان","Anna قانونی"]|x} );
    ( "person.fullName({\"firstName\":\"Anna\"})",
      7,
      {x|["Anna مستوفی","آقای Anna معین"]|x} );
    ("person.prefix(\"female\")", 42, {x|["خانم","دکتر"]|x});
    ("person.prefix(\"female\")", 1337, {x|["خانم","خانم"]|x});
    ("person.prefix(\"female\")", 7, {x|["خانم","دکتر"]|x});
    ("person.prefix(\"male\")", 42, {x|["آقای","دکتر"]|x});
    ("person.prefix(\"male\")", 1337, {x|["آقای","آقای"]|x});
    ("person.prefix(\"male\")", 7, {x|["آقای","دکتر"]|x});
    ("person.suffix()", 42, {x|["III","DVM"]|x});
    ("person.suffix()", 1337, {x|["I","Sr."]|x});
    ("person.suffix()", 7, {x|["Jr.","DDS"]|x});
    ( "location.zipCode({\"state\":\"CA\"})",
      42,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      1337,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"CA\"})",
      7,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      42,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      1337,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ( "location.zipCode({\"state\":\"ON\"})",
      7,
      {x|[{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"},{"error":"The locale data for 'location.postcode_by_state' are missing in this locale.\n  If this is a custom Faker instance, please make sure all required locales are used e.g. '[de_AT, de, en, base]'.\n  Please contribute the missing data to the project or use a locale/Faker instance that has these data.\n  For more information see https://fakerjs.dev/guide/localization.html"}]|x}
    );
    ("location.zipCode(\"###\")", 42, {x|["397","511"]|x});
    ("location.zipCode(\"###\")", 1337, {x|["212","435"]|x});
    ("location.zipCode(\"###\")", 7, {x|["074","795"]|x});
    ("location.state({\"abbreviated\":true})", 42, {x|["ME","WV"]|x});
    ("location.state({\"abbreviated\":true})", 1337, {x|["IN","DE"]|x});
    ("location.state({\"abbreviated\":true})", 7, {x|["AR","RI"]|x});
    ( "location.streetAddress(true)",
      42,
      {x|["کوچه رامین, پلاک 6  واحد 2","خیابان ستارخان, پلاک 7  واحد 9"]|x} );
    ( "location.streetAddress(true)",
      1337,
      {x|["کوچه اجاره دار, پلاک 53  3 طبقه","بلوار شهید مطهری, پلاک 46  واحد 9"]|x}
    );
    ( "location.streetAddress(true)",
      7,
      {x|["خیابان هویزه, پلاک 79  5 طبقه","خیابان قدس, پلاک 78  واحد 1"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      42,
      {x|["کوچه رامین, پلاک 6  واحد 2","خیابان ستارخان, پلاک 7  واحد 9"]|x} );
    ( "location.streetAddress({\"useFullAddress\":true})",
      1337,
      {x|["کوچه اجاره دار, پلاک 53  3 طبقه","بلوار شهید مطهری, پلاک 46  واحد 9"]|x}
    );
    ( "location.streetAddress({\"useFullAddress\":true})",
      7,
      {x|["خیابان هویزه, پلاک 79  5 طبقه","خیابان قدس, پلاک 78  واحد 1"]|x} );
    ("location.countryCode(\"alpha-3\")", 42, {x|["GUY","VCT"]|x});
    ("location.countryCode(\"alpha-3\")", 1337, {x|["ESH","COD"]|x});
    ("location.countryCode(\"alpha-3\")", 7, {x|["BEL","SYC"]|x});
    ("location.countryCode(\"numeric\")", 42, {x|["328","670"]|x});
    ("location.countryCode(\"numeric\")", 1337, {x|["732","180"]|x});
    ("location.countryCode(\"numeric\")", 7, {x|["056","690"]|x});
    ( "location.timeZone()",
      42,
      {x|["America/North_Dakota/Center","Pacific/Kosrae"]|x} );
    ( "location.timeZone()",
      1337,
      {x|["America/Guadeloupe","America/Argentina/San_Luis"]|x} );
    ("location.timeZone()", 7, {x|["Africa/Libreville","Europe/Gibraltar"]|x});
    ("date.month({\"abbreviated\":true})", 42, {x|["بهم","مهر"]|x});
    ("date.month({\"abbreviated\":true})", 1337, {x|["اسف","آذر"]|x});
    ("date.month({\"abbreviated\":true})", 7, {x|["آبا","فرو"]|x});
    ("date.month({\"context\":true})", 42, {x|["بهمن","مهر"]|x});
    ("date.month({\"context\":true})", 1337, {x|["اسفند","آذر"]|x});
    ("date.month({\"context\":true})", 7, {x|["آبان","فروردین"]|x});
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      42,
      {x|["بهم","مهر"]|x} );
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      1337,
      {x|["اسف","آذر"]|x} );
    ( "date.month({\"abbreviated\":true,\"context\":true})",
      7,
      {x|["آبا","فرو"]|x} );
    ("date.weekday({\"abbreviated\":true})", 42, {x|["س","ی"]|x});
    ("date.weekday({\"abbreviated\":true})", 1337, {x|["د","د"]|x});
    ("date.weekday({\"abbreviated\":true})", 7, {x|["ج","چ"]|x});
    ("date.weekday({\"context\":true})", 42, {x|["سه شنبه","یکشنبه"]|x});
    ("date.weekday({\"context\":true})", 1337, {x|["دوشنبه","دوشنبه"]|x});
    ("date.weekday({\"context\":true})", 7, {x|["جمعه","چهارشنبه"]|x});
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      42,
      {x|["س","ی"]|x} );
    ( "date.weekday({\"abbreviated\":true,\"context\":true})",
      1337,
      {x|["د","د"]|x} );
    ("date.weekday({\"abbreviated\":true,\"context\":true})", 7, {x|["ج","چ"]|x});
    ( "phone.number({\"style\":\"human\"})",
      42,
      {x|["035-97511086","071-09821135"]|x} );
    ( "phone.number({\"style\":\"human\"})",
      1337,
      {x|["026-12435297","021-36194773"]|x} );
    ( "phone.number({\"style\":\"human\"})",
      7,
      {x|["017-74795502","044-68302924"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      42,
      {x|["03597511086","07109821135"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      1337,
      {x|["02612435297","02136194773"]|x} );
    ( "phone.number({\"style\":\"national\"})",
      7,
      {x|["01774795502","04468302924"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      42,
      {x|["+983597511086","+987109821135"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      1337,
      {x|["+982612435297","+982136194773"]|x} );
    ( "phone.number({\"style\":\"international\"})",
      7,
      {x|["+981774795502","+984468302924"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      42,
      {x|["بارانی","ثانوی"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      1337,
      {x|["آسان","غمگین"]|x} );
    ( "word.adjective({\"length\":{\"min\":3,\"max\":6}})",
      7,
      {x|["داغ","بی‌بو"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      42,
      {x|["دندان","شامپو"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      1337,
      {x|["حیوان","پنجره"]|x} );
    ( "word.noun({\"length\":5,\"strategy\":\"closest\"})",
      7,
      {x|["آسمان","نظارت"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      42,
      {x|["آمدن","بودن"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      1337,
      {x|["آمدن","رفتن"]|x} );
    ( "word.verb({\"length\":20,\"strategy\":\"shortest\"})",
      7,
      {x|["رفتن","گفتن"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      42,
      {x|["even","خواب"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      1337,
      {x|["بلکه","زیرا"]|x} );
    ( "word.sample({\"length\":4,\"strategy\":\"any-length\"})",
      7,
      {x|["دیدن","بدون"]|x} );
    ( "word.words(5)",
      42,
      {x|["bleakly پنجره وایسا اِی وای همچون","آهان اِی وای اصلی بنابراین به ترتیب"]|x}
    );
    ( "word.words(5)",
      1337,
      {x|["بلکه همچون تازه صندلی به عنوان","safely دانشگاه actually رفتن vaguely"]|x}
    );
    ( "word.words(5)",
      7,
      {x|["راه انداختن درباره وایسا نویسنده نزد","برنده شدن تاریک آه نوشیدن باز"]|x}
    );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      42,
      {x|["لازم","مورد"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      1337,
      {x|["بلکه","و با"]|x} );
    ( "lorem.word({\"length\":4,\"strategy\":\"closest\"})",
      7,
      {x|["صنعت","تایپ"]|x} );
    ( "lorem.sentences(3)",
      42,
      {x|["دنیای داشت بیشتری را طراحان طراحان. حروفچینی بیشتری را می توان. اساسا به پایان بلکه.","چاپگرها و برای جامعه کتابهای. برای استفاده لازم و کاربردهای شصت و سه درصد. و متون فراوان نرم افزارها با، برای است تولید دنیای طراحی."]|x}
    );
    ( "lorem.sentences(3)",
      1337,
      {x|["گرافیک آنچنان شصت و سه درصد شرایط جامعه. اساسا داشت چاپ با هدف رایانه ای. مورد زیادی ارائه ارائه.","می باشد تا با، تمام چاپگرها که،. شناخت است ابزارهای کاربردی و متون و به پایان چاپگرها طراحی. شناخت فراوان ایپسوم داشت قرار گیرد گرافیک."]|x}
    );
    ( "lorem.sentences(3)",
      7,
      {x|["موجود زیادی امید. و شناخت سادگی و سطر شناخت ایجاد راهکارها متنوع تولید که،. بلکه شصت و سه درصد پیوسته متن بیشتری را دنیای و مجله متخصصان جوابگوی و با.","که در زبان فارسی گذشته بلکه و آینده متنوع حال. به پایان و دشواری و برای می طلبد آنچنان. مورد نیاز و فرهنگ پیشرو و کاربردهای شصت و سه درصد امید ابزارهای کاربردی."]|x}
    );
    ( "lorem.paragraphs(2)",
      42,
      {x|["دنیای داشت بیشتری را طراحان طراحان. حروفچینی بیشتری را می توان. اساسا به پایان بلکه.\nچاپگرها و برای جامعه کتابهای. برای استفاده لازم و کاربردهای شصت و سه درصد. و متون فراوان نرم افزارها با، برای است تولید دنیای طراحی.","و برای از ایجاد زیادی چاپ شناخت ساختگی جوابگوی و سطر. و برای جامعه متخصصان چاپگرها اساسا و دشواری اهل اصلی. پیوسته نامفهوم، و متون با، شرایط با هدف آنچنان.\nمورد نیاز که، متخصصان استفاده راهکارها سادگی مورد و دشواری و متون. سخت در این صورت امید. سادگی مورد نیاز چاپ شامل رایانه ای فعلی تولید و برای شرایط."]|x}
    );
    ( "lorem.paragraphs(2)",
      1337,
      {x|["گرافیک آنچنان شصت و سه درصد شرایط جامعه. اساسا داشت چاپ با هدف رایانه ای. مورد زیادی ارائه ارائه.\nمی باشد تا با، تمام چاپگرها که،. شناخت است ابزارهای کاربردی و متون و به پایان چاپگرها طراحی. شناخت فراوان ایپسوم داشت قرار گیرد گرافیک.","متنوع کرد لورم و کاربردهای. ارائه مورد نیاز در این صورت. اساسا به پایان برای می طلبد قرار گیرد ستون.\nنامفهوم، اهل اساسا. تکنولوژی امید لورم تمام در زبان فارسی چاپگرها. سوالات گرافیک سوالات شرایط در این صورت و سطر جامعه است."]|x}
    );
    ( "lorem.paragraphs(2)",
      7,
      {x|["موجود زیادی امید. و شناخت سادگی و سطر شناخت ایجاد راهکارها متنوع تولید که،. بلکه شصت و سه درصد پیوسته متن بیشتری را دنیای و مجله متخصصان جوابگوی و با.\nکه در زبان فارسی گذشته بلکه و آینده متنوع حال. به پایان و دشواری و برای می طلبد آنچنان. مورد نیاز و فرهنگ پیشرو و کاربردهای شصت و سه درصد امید ابزارهای کاربردی.","چاپگرها داشت می باشد می باشد علی الخصوص جامعه ابزارهای کاربردی لورم از می توان. کرد طراحی ایجاد با، و برای نرم افزارها و مجله. دنیای  و زمان حال به پایان و با و برای گذشته که و آینده استفاده.\nشرایط لازم گرافیک ابزارهای کاربردی زیادی. ارائه جامعه شصت و سه درصد موجود دستاوردهای ایجاد راهکارها اهل ساختگی. آنچنان حال ارائه می توان طراحان و فرهنگ پیشرو سادگی مورد نیاز سخت کتابهای."]|x}
    );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      42,
      {x|["Jurgen_60degard@hotmail.com","Jurgen.60degard@gmail.com"]|x} );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      1337,
      {x|["Jurgen.60degard27@gmail.com","Jurgen_60degard@gmail.com"]|x} );
    ( "internet.email({\"firstName\":\"Jürgen\",\"lastName\":\"Ødegård\"})",
      7,
      {x|["Jurgen_60degard@gmail.com","Jurgen_60degard50@yahoo.com"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      42,
      {x|["Anna.8xukasz","Anna_8xukasz15"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      1337,
      {x|["Anna.8xukasz15","Anna.8xukasz"]|x} );
    ( "internet.username({\"firstName\":\"Анна\",\"lastName\":\"Łukasz\"})",
      7,
      {x|["Anna.8xukasz77","Anna_8xukasz"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      42,
      {x|["Zoë15","Zoë_میردامادی2"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      1337,
      {x|["Zoë.قهرمان","Zoë.هاشمیرفسنجانی"]|x} );
    ( "internet.displayName({\"firstName\":\"Zoë\"})",
      7,
      {x|["Zoë_مستوفی","Zoë.قمیشی67"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      42,
      {x|["mhra18zra60@hotmail.com","drya*mrtdwy61@yahoo.com"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      1337,
      {x|["frank?qanwny73@gmail.com","mhyar_mhmdy76@gmail.com"]|x} );
    ( "internet.email({\"allowSpecialCharacters\":true})",
      7,
      {x|["mhdy.meyn@gmail.com","chkawk60@hotmail.com"]|x} );
    ("internet.domainWord()", 42, {x|["peebwps-feehnlhp","lufnp-byzv"]|x});
    ("internet.domainWord()", 1337, {x|["lingz-qdzlu","ptehrm-nvey"]|x});
    ("internet.domainWord()", 7, {x|["szonbg-jbhxflya","oxdnt-mjmjv"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 42, {x|["€375.15","€599.09"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 1337, {x|["€262.79","€459.85"]|x});
    ("commerce.price({\"symbol\":\"€\"})", 7, {x|["€77.29","€723.75"]|x});
    ( "commerce.productName()",
      42,
      {x|["شلوار یخ زده لطیف","مرغ بتنی باور نکردنی"]|x} );
    ( "commerce.productName()",
      1337,
      {x|["سالاد بتنی بدون محدودیت","ماشین فلزی خوش طعم"]|x} );
    ( "commerce.productName()",
      7,
      {x|["تن ماهی کتان خارق العاده","پیتزا یخ زده خوش طعم"]|x} );
    ( "company.name()",
      42,
      {x|["میردامادی, عصار و نوبختی","فریاد شرکت با مسئولیت محدود"]|x} );
    ( "company.name()",
      1337,
      {x|["مصباح و پسران","هاشمی رفسنجانی, ناظری و مستوفی"]|x} );
    ("company.name()", 7, {x|["هاشمی گروه","قمیشی, هومن و قهرمانی"]|x});
    ("finance.currencyName()", 42, {x|["ریال ایران","کرون سوئد"]|x});
    ("finance.currencyName()", 1337, {x|["کرون چک","مانات آذربایجان"]|x});
    ("finance.currencyName()", 7, {x|["پزو آرژانتین","ریال قطر"]|x});
    ( "finance.creditCardNumber(\"visa\")",
      42,
      {x|["4975110867099","4211-3542-6123-4718"]|x} );
    ( "finance.creditCardNumber(\"visa\")",
      1337,
      {x|["4124352971364","4947734571266"]|x} );
    ( "finance.creditCardNumber(\"visa\")",
      7,
      {x|["4747955024684","4029249069258"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      42,
      {x|["2696-7511-0867-0988","2311-1354-2612-3471"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      1337,
      {x|["2300-2435-2971-3611","5377-3457-1264-1417"]|x} );
    ( "finance.creditCardNumber(\"mastercard\")",
      7,
      {x|["2610-4795-5024-6833","2365-9249-0692-5918"]|x} );
    ("animal.type()", 42, {x|["frog","whale"]|x});
    ("animal.type()", 1337, {x|["eagle","cow"]|x});
    ("animal.type()", 7, {x|["bird","rhinoceros"]|x});
    ( "system.fileName({\"extensionCount\":2})",
      42,
      {x|["unnaturally_dreamily.mar.xlw","___________.dot.m1v"]|x} );
    ( "system.fileName({\"extensionCount\":2})",
      1337,
      {x|["____.jpg.distz","_______________.lrf.vsw"]|x} );
    ( "system.fileName({\"extensionCount\":2})",
      7,
      {x|["__.xla.xhtml","__________________.xlsx.sh"]|x} );
    ( "food.dish()",
      42,
      {x|["Jicama Salad","Tangy Parsnip And White Flour Bowl"]|x} );
    ( "food.dish()",
      1337,
      {x|["Moist Green Beans And White Wine Vinegar Bowl","Bruschette With Tomato"]|x}
    );
    ("food.dish()", 7, {x|["Parsley-rubbed Ostrich Salad","Baba Ganoush"]|x});
    ( "music.songName()",
      42,
      {x|["I Honestly Love You","Why Do Fools Fall in Love?"]|x} );
    ("music.songName()", 1337, {x|["Frankenstein","Cars"]|x});
    ("music.songName()", 7, {x|["Bad Day","Take Me Home, Country Roads"]|x});
    ("book.title()", 42, {x|["Lord Jim","Tropic of Cancer"]|x});
    ("book.title()", 1337, {x|["Gone with the Wind","Candide"]|x});
    ( "book.title()",
      7,
      {x|["All Quiet on the Western Front","The Pickwick Papers"]|x} );
    ("vehicle.vehicle()", 42, {x|["رولز رویس گلف","نیسان مالیبو"]|x});
    ("vehicle.vehicle()", 1337, {x|["جگوار اسکالید","جگوار سیویک"]|x});
    ("vehicle.vehicle()", 7, {x|["بنتلی کروت","فراری چلنجر"]|x});
  ]
