(* GENERATED by tools/gen_fixtures.mjs from tools/cases/sweep.mjs - do not edit. *)

let groups =
  [
    ("sweep_af_ZA", Expected_sweep_af_ZA.locale, Expected_sweep_af_ZA.cases);
    ("sweep_ar", Expected_sweep_ar.locale, Expected_sweep_ar.cases);
    ("sweep_az", Expected_sweep_az.locale, Expected_sweep_az.cases);
    ("sweep_base", Expected_sweep_base.locale, Expected_sweep_base.cases);
    ("sweep_bn_BD", Expected_sweep_bn_BD.locale, Expected_sweep_bn_BD.cases);
    ("sweep_cs_CZ", Expected_sweep_cs_CZ.locale, Expected_sweep_cs_CZ.cases);
    ("sweep_cy", Expected_sweep_cy.locale, Expected_sweep_cy.cases);
    ("sweep_da", Expected_sweep_da.locale, Expected_sweep_da.cases);
    ("sweep_de", Expected_sweep_de.locale, Expected_sweep_de.cases);
    ("sweep_de_AT", Expected_sweep_de_AT.locale, Expected_sweep_de_AT.cases);
    ("sweep_de_CH", Expected_sweep_de_CH.locale, Expected_sweep_de_CH.cases);
    ("sweep_dv", Expected_sweep_dv.locale, Expected_sweep_dv.cases);
    ("sweep_el", Expected_sweep_el.locale, Expected_sweep_el.cases);
    ("sweep_en", Expected_sweep_en.locale, Expected_sweep_en.cases);
    ("sweep_en_AU", Expected_sweep_en_AU.locale, Expected_sweep_en_AU.cases);
    ( "sweep_en_AU_ocker",
      Expected_sweep_en_AU_ocker.locale,
      Expected_sweep_en_AU_ocker.cases );
    ( "sweep_en_BORK",
      Expected_sweep_en_BORK.locale,
      Expected_sweep_en_BORK.cases );
    ("sweep_en_CA", Expected_sweep_en_CA.locale, Expected_sweep_en_CA.cases);
    ("sweep_en_GB", Expected_sweep_en_GB.locale, Expected_sweep_en_GB.cases);
    ("sweep_en_GH", Expected_sweep_en_GH.locale, Expected_sweep_en_GH.cases);
    ("sweep_en_HK", Expected_sweep_en_HK.locale, Expected_sweep_en_HK.cases);
    ("sweep_en_IE", Expected_sweep_en_IE.locale, Expected_sweep_en_IE.cases);
    ("sweep_en_IN", Expected_sweep_en_IN.locale, Expected_sweep_en_IN.cases);
    ("sweep_en_NG", Expected_sweep_en_NG.locale, Expected_sweep_en_NG.cases);
    ("sweep_en_NP", Expected_sweep_en_NP.locale, Expected_sweep_en_NP.cases);
    ("sweep_en_US", Expected_sweep_en_US.locale, Expected_sweep_en_US.cases);
    ("sweep_en_ZA", Expected_sweep_en_ZA.locale, Expected_sweep_en_ZA.cases);
    ("sweep_eo", Expected_sweep_eo.locale, Expected_sweep_eo.cases);
    ("sweep_es", Expected_sweep_es.locale, Expected_sweep_es.cases);
    ("sweep_es_MX", Expected_sweep_es_MX.locale, Expected_sweep_es_MX.cases);
    ("sweep_fa", Expected_sweep_fa.locale, Expected_sweep_fa.cases);
    ("sweep_fi", Expected_sweep_fi.locale, Expected_sweep_fi.cases);
    ("sweep_fr", Expected_sweep_fr.locale, Expected_sweep_fr.cases);
    ("sweep_fr_BE", Expected_sweep_fr_BE.locale, Expected_sweep_fr_BE.cases);
    ("sweep_fr_CA", Expected_sweep_fr_CA.locale, Expected_sweep_fr_CA.cases);
    ("sweep_fr_CH", Expected_sweep_fr_CH.locale, Expected_sweep_fr_CH.cases);
    ("sweep_fr_LU", Expected_sweep_fr_LU.locale, Expected_sweep_fr_LU.cases);
    ("sweep_fr_SN", Expected_sweep_fr_SN.locale, Expected_sweep_fr_SN.cases);
    ("sweep_he", Expected_sweep_he.locale, Expected_sweep_he.cases);
    ("sweep_hr", Expected_sweep_hr.locale, Expected_sweep_hr.cases);
    ("sweep_hu", Expected_sweep_hu.locale, Expected_sweep_hu.cases);
    ("sweep_hy", Expected_sweep_hy.locale, Expected_sweep_hy.cases);
    ("sweep_id_ID", Expected_sweep_id_ID.locale, Expected_sweep_id_ID.cases);
    ("sweep_it", Expected_sweep_it.locale, Expected_sweep_it.cases);
    ("sweep_ja", Expected_sweep_ja.locale, Expected_sweep_ja.cases);
    ("sweep_ka_GE", Expected_sweep_ka_GE.locale, Expected_sweep_ka_GE.cases);
    ("sweep_ko", Expected_sweep_ko.locale, Expected_sweep_ko.cases);
    ("sweep_ku_ckb", Expected_sweep_ku_ckb.locale, Expected_sweep_ku_ckb.cases);
    ( "sweep_ku_kmr_latin",
      Expected_sweep_ku_kmr_latin.locale,
      Expected_sweep_ku_kmr_latin.cases );
    ("sweep_lv", Expected_sweep_lv.locale, Expected_sweep_lv.cases);
    ("sweep_mk", Expected_sweep_mk.locale, Expected_sweep_mk.cases);
    ( "sweep_mn_MN_cyrl",
      Expected_sweep_mn_MN_cyrl.locale,
      Expected_sweep_mn_MN_cyrl.cases );
    ("sweep_nb_NO", Expected_sweep_nb_NO.locale, Expected_sweep_nb_NO.cases);
    ("sweep_ne", Expected_sweep_ne.locale, Expected_sweep_ne.cases);
    ("sweep_nl", Expected_sweep_nl.locale, Expected_sweep_nl.cases);
    ("sweep_nl_BE", Expected_sweep_nl_BE.locale, Expected_sweep_nl_BE.cases);
    ("sweep_pl", Expected_sweep_pl.locale, Expected_sweep_pl.cases);
    ("sweep_pt_BR", Expected_sweep_pt_BR.locale, Expected_sweep_pt_BR.cases);
    ("sweep_pt_PT", Expected_sweep_pt_PT.locale, Expected_sweep_pt_PT.cases);
    ("sweep_ro", Expected_sweep_ro.locale, Expected_sweep_ro.cases);
    ("sweep_ro_MD", Expected_sweep_ro_MD.locale, Expected_sweep_ro_MD.cases);
    ("sweep_ru", Expected_sweep_ru.locale, Expected_sweep_ru.cases);
    ("sweep_sk", Expected_sweep_sk.locale, Expected_sweep_sk.cases);
    ("sweep_sl_SI", Expected_sweep_sl_SI.locale, Expected_sweep_sl_SI.cases);
    ( "sweep_sr_RS_latin",
      Expected_sweep_sr_RS_latin.locale,
      Expected_sweep_sr_RS_latin.cases );
    ("sweep_sv", Expected_sweep_sv.locale, Expected_sweep_sv.cases);
    ("sweep_ta_IN", Expected_sweep_ta_IN.locale, Expected_sweep_ta_IN.cases);
    ("sweep_th", Expected_sweep_th.locale, Expected_sweep_th.cases);
    ("sweep_tr", Expected_sweep_tr.locale, Expected_sweep_tr.cases);
    ("sweep_uk", Expected_sweep_uk.locale, Expected_sweep_uk.cases);
    ("sweep_ur", Expected_sweep_ur.locale, Expected_sweep_ur.cases);
    ( "sweep_uz_UZ_latin",
      Expected_sweep_uz_UZ_latin.locale,
      Expected_sweep_uz_UZ_latin.cases );
    ("sweep_vi", Expected_sweep_vi.locale, Expected_sweep_vi.cases);
    ("sweep_yo_NG", Expected_sweep_yo_NG.locale, Expected_sweep_yo_NG.cases);
    ("sweep_zh_CN", Expected_sweep_zh_CN.locale, Expected_sweep_zh_CN.cases);
    ("sweep_zh_TW", Expected_sweep_zh_TW.locale, Expected_sweep_zh_TW.cases);
    ("sweep_zu_ZA", Expected_sweep_zu_ZA.locale, Expected_sweep_zu_ZA.cases);
  ]
