(* GENERATED by tools/gen_fixtures.mjs from tools/cases/l10n.mjs - do not edit. *)

let groups =
  [
    ("l10n_af_ZA", Expected_l10n_af_ZA.locale, Expected_l10n_af_ZA.cases);
    ("l10n_ar", Expected_l10n_ar.locale, Expected_l10n_ar.cases);
    ("l10n_az", Expected_l10n_az.locale, Expected_l10n_az.cases);
    ("l10n_base", Expected_l10n_base.locale, Expected_l10n_base.cases);
    ("l10n_bn_BD", Expected_l10n_bn_BD.locale, Expected_l10n_bn_BD.cases);
    ("l10n_cs_CZ", Expected_l10n_cs_CZ.locale, Expected_l10n_cs_CZ.cases);
    ("l10n_cy", Expected_l10n_cy.locale, Expected_l10n_cy.cases);
    ("l10n_da", Expected_l10n_da.locale, Expected_l10n_da.cases);
    ("l10n_de", Expected_l10n_de.locale, Expected_l10n_de.cases);
    ("l10n_de_AT", Expected_l10n_de_AT.locale, Expected_l10n_de_AT.cases);
    ("l10n_de_CH", Expected_l10n_de_CH.locale, Expected_l10n_de_CH.cases);
    ("l10n_dv", Expected_l10n_dv.locale, Expected_l10n_dv.cases);
    ("l10n_el", Expected_l10n_el.locale, Expected_l10n_el.cases);
    ("l10n_en", Expected_l10n_en.locale, Expected_l10n_en.cases);
    ("l10n_en_AU", Expected_l10n_en_AU.locale, Expected_l10n_en_AU.cases);
    ( "l10n_en_AU_ocker",
      Expected_l10n_en_AU_ocker.locale,
      Expected_l10n_en_AU_ocker.cases );
    ("l10n_en_BORK", Expected_l10n_en_BORK.locale, Expected_l10n_en_BORK.cases);
    ("l10n_en_CA", Expected_l10n_en_CA.locale, Expected_l10n_en_CA.cases);
    ("l10n_en_GB", Expected_l10n_en_GB.locale, Expected_l10n_en_GB.cases);
    ("l10n_en_GH", Expected_l10n_en_GH.locale, Expected_l10n_en_GH.cases);
    ("l10n_en_HK", Expected_l10n_en_HK.locale, Expected_l10n_en_HK.cases);
    ("l10n_en_IE", Expected_l10n_en_IE.locale, Expected_l10n_en_IE.cases);
    ("l10n_en_IN", Expected_l10n_en_IN.locale, Expected_l10n_en_IN.cases);
    ("l10n_en_NG", Expected_l10n_en_NG.locale, Expected_l10n_en_NG.cases);
    ("l10n_en_NP", Expected_l10n_en_NP.locale, Expected_l10n_en_NP.cases);
    ("l10n_en_US", Expected_l10n_en_US.locale, Expected_l10n_en_US.cases);
    ("l10n_en_ZA", Expected_l10n_en_ZA.locale, Expected_l10n_en_ZA.cases);
    ("l10n_eo", Expected_l10n_eo.locale, Expected_l10n_eo.cases);
    ("l10n_es", Expected_l10n_es.locale, Expected_l10n_es.cases);
    ("l10n_es_MX", Expected_l10n_es_MX.locale, Expected_l10n_es_MX.cases);
    ("l10n_fa", Expected_l10n_fa.locale, Expected_l10n_fa.cases);
    ("l10n_fi", Expected_l10n_fi.locale, Expected_l10n_fi.cases);
    ("l10n_fr", Expected_l10n_fr.locale, Expected_l10n_fr.cases);
    ("l10n_fr_BE", Expected_l10n_fr_BE.locale, Expected_l10n_fr_BE.cases);
    ("l10n_fr_CA", Expected_l10n_fr_CA.locale, Expected_l10n_fr_CA.cases);
    ("l10n_fr_CH", Expected_l10n_fr_CH.locale, Expected_l10n_fr_CH.cases);
    ("l10n_fr_LU", Expected_l10n_fr_LU.locale, Expected_l10n_fr_LU.cases);
    ("l10n_fr_SN", Expected_l10n_fr_SN.locale, Expected_l10n_fr_SN.cases);
    ("l10n_he", Expected_l10n_he.locale, Expected_l10n_he.cases);
    ("l10n_hr", Expected_l10n_hr.locale, Expected_l10n_hr.cases);
    ("l10n_hu", Expected_l10n_hu.locale, Expected_l10n_hu.cases);
    ("l10n_hy", Expected_l10n_hy.locale, Expected_l10n_hy.cases);
    ("l10n_id_ID", Expected_l10n_id_ID.locale, Expected_l10n_id_ID.cases);
    ("l10n_it", Expected_l10n_it.locale, Expected_l10n_it.cases);
    ("l10n_ja", Expected_l10n_ja.locale, Expected_l10n_ja.cases);
    ("l10n_ka_GE", Expected_l10n_ka_GE.locale, Expected_l10n_ka_GE.cases);
    ("l10n_ko", Expected_l10n_ko.locale, Expected_l10n_ko.cases);
    ("l10n_ku_ckb", Expected_l10n_ku_ckb.locale, Expected_l10n_ku_ckb.cases);
    ( "l10n_ku_kmr_latin",
      Expected_l10n_ku_kmr_latin.locale,
      Expected_l10n_ku_kmr_latin.cases );
    ("l10n_lv", Expected_l10n_lv.locale, Expected_l10n_lv.cases);
    ("l10n_mk", Expected_l10n_mk.locale, Expected_l10n_mk.cases);
    ( "l10n_mn_MN_cyrl",
      Expected_l10n_mn_MN_cyrl.locale,
      Expected_l10n_mn_MN_cyrl.cases );
    ("l10n_nb_NO", Expected_l10n_nb_NO.locale, Expected_l10n_nb_NO.cases);
    ("l10n_ne", Expected_l10n_ne.locale, Expected_l10n_ne.cases);
    ("l10n_nl", Expected_l10n_nl.locale, Expected_l10n_nl.cases);
    ("l10n_nl_BE", Expected_l10n_nl_BE.locale, Expected_l10n_nl_BE.cases);
    ("l10n_pl", Expected_l10n_pl.locale, Expected_l10n_pl.cases);
    ("l10n_pt_BR", Expected_l10n_pt_BR.locale, Expected_l10n_pt_BR.cases);
    ("l10n_pt_PT", Expected_l10n_pt_PT.locale, Expected_l10n_pt_PT.cases);
    ("l10n_ro", Expected_l10n_ro.locale, Expected_l10n_ro.cases);
    ("l10n_ro_MD", Expected_l10n_ro_MD.locale, Expected_l10n_ro_MD.cases);
    ("l10n_ru", Expected_l10n_ru.locale, Expected_l10n_ru.cases);
    ("l10n_sk", Expected_l10n_sk.locale, Expected_l10n_sk.cases);
    ("l10n_sl_SI", Expected_l10n_sl_SI.locale, Expected_l10n_sl_SI.cases);
    ( "l10n_sr_RS_latin",
      Expected_l10n_sr_RS_latin.locale,
      Expected_l10n_sr_RS_latin.cases );
    ("l10n_sv", Expected_l10n_sv.locale, Expected_l10n_sv.cases);
    ("l10n_ta_IN", Expected_l10n_ta_IN.locale, Expected_l10n_ta_IN.cases);
    ("l10n_th", Expected_l10n_th.locale, Expected_l10n_th.cases);
    ("l10n_tr", Expected_l10n_tr.locale, Expected_l10n_tr.cases);
    ("l10n_uk", Expected_l10n_uk.locale, Expected_l10n_uk.cases);
    ("l10n_ur", Expected_l10n_ur.locale, Expected_l10n_ur.cases);
    ( "l10n_uz_UZ_latin",
      Expected_l10n_uz_UZ_latin.locale,
      Expected_l10n_uz_UZ_latin.cases );
    ("l10n_vi", Expected_l10n_vi.locale, Expected_l10n_vi.cases);
    ("l10n_yo_NG", Expected_l10n_yo_NG.locale, Expected_l10n_yo_NG.cases);
    ("l10n_zh_CN", Expected_l10n_zh_CN.locale, Expected_l10n_zh_CN.cases);
    ("l10n_zh_TW", Expected_l10n_zh_TW.locale, Expected_l10n_zh_TW.cases);
    ("l10n_zu_ZA", Expected_l10n_zu_ZA.locale, Expected_l10n_zu_ZA.cases);
  ]
