(* GENERATED by tools/gen_fixtures.mjs from tools/cases/database.mjs - do not edit. *)

let locale = "en"

let cases =
  [
    ("column", 42, {x|["group","updatedAt","status"]|x});
    ("column", 1337, {x|["createdAt","comment","createdAt"]|x});
    ("column", 7, {x|["category","status","id"]|x});
    ("type", 42, {x|["double","tinyint","set"]|x});
    ("type", 1337, {x|["datetime","blob","datetime"]|x});
    ("type", 7, {x|["binary","smallint","float"]|x});
    ("collation", 42, {x|["cp1250_bin","utf8_unicode_ci","utf8_general_ci"]|x});
    ( "collation",
      1337,
      {x|["ascii_general_ci","ascii_general_ci","ascii_general_ci"]|x} );
    ("collation", 7, {x|["ascii_bin","utf8_general_ci","cp1250_general_ci"]|x});
    ("engine", 42, {x|["CSV","MyISAM","MEMORY"]|x});
    ("engine", 1337, {x|["BLACKHOLE","ARCHIVE","BLACKHOLE"]|x});
    ("engine", 7, {x|["ARCHIVE","MEMORY","CSV"]|x});
    ( "mongodbObjectId",
      42,
      {x|["8ead331ddf0fc4446b96d368","ab4bd1d31efb62f92a0e5e6b","c4fbedde140785c76b3b1fa4"]|x}
    );
    ( "mongodbObjectId",
      1337,
      {x|["536a7b5fa28d2f9bb79ca46e","a394bc4f9bb0af328f081b7f","afcdcf501efa7f0ae4ee3e7f"]|x}
    );
    ( "mongodbObjectId",
      7,
      {x|["1b9ffbb15aeb816e49e0de5c","e2baea4a8a8ca6c697e8af9d","3a99db902fbfff16d5fecac2"]|x}
    );
    ( "fake",
      42,
      {x|["updatedAt point 331ddf0fc4446b96d368ab4b","avatar boolean 1efb62f92a0e5e6bc4fbedde","comment decimal 85c76b3b1fa40bfaa172cd71"]|x}
    );
    ( "fake",
      1337,
      {x|["comment geometry 7b5fa28d2f9bb79ca46ea394","title tinyint 9bb0af328f081b7fafcdcf50","updatedAt geometry 7f0ae4ee3e7f5b3a98bafb7e"]|x}
    );
    ( "fake",
      7,
      {x|["status set fbb15aeb816e49e0de5ce2ba","id geometry 8a8ca6c697e8af9d3a99db90","phone serial ff16d5fecac26aaa3776399b"]|x}
    );
  ]
