(* GENERATED by tools/gen_fixtures.mjs from tools/cases/music.mjs - do not edit. *)

let locale = "en"

let cases = [
  ("album", 42, {x|["Heard It In A Past Life","Vida","Schwarzes Herz"]|x});
  ("album", 1337, {x|["Dulce Beat","Carnival","El Mal Querer"]|x});
  ("album", 7, {x|["Aura","Stay Dangerous","Innuendo"]|x});
  ("artist", 42, {x|["James TW","Vanessa Carlton","Ryan Lewis"]|x});
  ("artist", 1337, {x|["Evanescence","Cher","Five Finger Death Punch"]|x});
  ("artist", 7, {x|["Bachman-Turner Overdrive","Smokey Robinson","Karan Aujla"]|x});
  ("genre", 42, {x|["German Folk","Tex-Mex","Pop"]|x});
  ("genre", 1337, {x|["Drinking Songs","Chicago House","Dubstep"]|x});
  ("genre", 7, {x|["Bebop","Qawwali","Hardcore Rap"]|x});
  ("songName", 42, {x|["I Honestly Love You","Why Do Fools Fall in Love?","Somethin' Stupid"]|x});
  ("songName", 1337, {x|["Frankenstein","Cars","Glamorous"]|x});
  ("songName", 7, {x|["Bad Day","Take Me Home, Country Roads","Jessie's Girl"]|x});
  ("fake", 42, {x|["Vida|Nate Smith|Chicago Blues|Another Brick in the Wall (part 2)|","Nine Track Mind|Agust D|Rocksteady|Don't Leave Me This Way|","Colour Vision|Luan Santana|Easter|Paint it Black|"]|x});
  ("fake", 1337, {x|["Carnival|Kings of Leon|Jam Bands|Frankenstein|","Seal The Deal & Let's Boogie|Jeezy|CCM|You Light Up My Life|","Sublime|Isaac Hayes|Mainstream Jazz|Summer in the City|"]|x});
  ("fake", 7, {x|["Stay Dangerous|Roger Miller|Karaoke|Lose Yourself|","Editorial|Quinn XCII|Glam Rock|Are You Lonesome Tonight?|","Too Hard|Key Glock|Afrobeat|One Bad Apple|"]|x});
]
